import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedfotoWidget1.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedPesananmasukWidget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedDikirimWidget1.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedMailinbox1Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedKeranjangWidget12.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedWishlistWidget6.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedLogOutWidget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedLine120Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedSavemoney1Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedLine122Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedBelumbayarWidget1.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedLine124Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedKrisnantoWidget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedAtasWidget18.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedLogout1Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedLike1Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedBeripenilaiankomentarWidget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedKatalogSayaWidget2.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedPickupcar1Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedLine121Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedBadge1Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedFooterWidget2.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedShoppingcart1Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedRectangle170Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedPencil1Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedCatalogue1Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget10/generated/GeneratedLine123Widget.dart';

/* Frame Akun
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAkunWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1540.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1540.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 200.0,
                              child: GeneratedAtasWidget18(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 280.0,
                              child: GeneratedRectangle170Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 230.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 220.0,
                              child: GeneratedfotoWidget1(),
                            ),
                            Positioned(
                              left: 340.0,
                              top: 297.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 91.0,
                              child: GeneratedKrisnantoWidget(),
                            ),
                            Positioned(
                              left: 1160.0,
                              top: 314.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 63.0,
                              child: GeneratedPencil1Widget(),
                            ),
                            Positioned(
                              left: 1159.9937744140625,
                              top: 379.4998474121094,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 5.0,
                              child: GeneratedLine120Widget(),
                            ),
                            Positioned(
                              left: 252.0,
                              top: 606.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 22.0,
                              child: GeneratedPesananmasukWidget(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 724.0,
                              right: null,
                              bottom: null,
                              width: 156.0,
                              height: 49.0,
                              child: GeneratedKeranjangWidget12(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 863.0,
                              right: null,
                              bottom: null,
                              width: 196.0,
                              height: 46.0,
                              child: GeneratedKatalogSayaWidget2(),
                            ),
                            Positioned(
                              left: 220.0,
                              top: 1008.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 46.0,
                              child: GeneratedLogOutWidget(),
                            ),
                            Positioned(
                              left: 479.0,
                              top: 606.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 22.0,
                              child: GeneratedBelumbayarWidget1(),
                            ),
                            Positioned(
                              left: 696.0,
                              top: 606.0,
                              right: null,
                              bottom: null,
                              width: 54.0,
                              height: 22.0,
                              child: GeneratedDikirimWidget1(),
                            ),
                            Positioned(
                              left: 880.0,
                              top: 606.0,
                              right: null,
                              bottom: null,
                              width: 113.0,
                              height: 44.0,
                              child: GeneratedBeripenilaiankomentarWidget(),
                            ),
                            Positioned(
                              left: 1111.0,
                              top: 606.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 22.0,
                              child: GeneratedWishlistWidget6(),
                            ),
                            Positioned(
                              left: 479.0,
                              top: 502.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 96.0,
                              child: GeneratedSavemoney1Widget(),
                            ),
                            Positioned(
                              left: 673.0,
                              top: 504.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedPickupcar1Widget(),
                            ),
                            Positioned(
                              left: 885.0,
                              top: 504.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 92.0,
                              child: GeneratedBadge1Widget(),
                            ),
                            Positioned(
                              left: 1099.0,
                              top: 522.0,
                              right: null,
                              bottom: null,
                              width: 79.0,
                              height: 79.0,
                              child: GeneratedLike1Widget(),
                            ),
                            Positioned(
                              left: 259.0,
                              top: 502.0,
                              right: null,
                              bottom: null,
                              width: 101.0,
                              height: 104.0,
                              child: GeneratedMailinbox1Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 681.0,
                              right: null,
                              bottom: null,
                              width: 1320.0,
                              height: 2.0,
                              child: GeneratedLine121Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 820.0,
                              right: null,
                              bottom: null,
                              width: 1320.0,
                              height: 2.0,
                              child: GeneratedLine122Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 960.0,
                              right: null,
                              bottom: null,
                              width: 1320.0,
                              height: 2.0,
                              child: GeneratedLine123Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 1100.0,
                              right: null,
                              bottom: null,
                              width: 1320.0,
                              height: 2.0,
                              child: GeneratedLine124Widget(),
                            ),
                            Positioned(
                              left: 67.0,
                              top: 987.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 85.0,
                              child: GeneratedLogout1Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 830.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 110.0,
                              child: GeneratedCatalogue1Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 696.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedShoppingcart1Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1259.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 281.0,
                              child: GeneratedFooterWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
