import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedDeskripsiProdukDesainDasborPenuhBaruyangMencolokTipe15G3.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedUnggahWidget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/Generated2020Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedHapusWidget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedRectangle663Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedRectangle666Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedRectangle671Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedRectangle667Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/Generated15Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedToyotaWidget11.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedBlackMatteSilverWidget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedRectangle665Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedRectangle670Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedRectangle738Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedToyotaAllNewAvanzaWidget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedAtaslogoWidget26.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedRectangle672Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedRectangle664Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedRectangle669Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedRectangle668Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget1/generated/GeneratedMobilBaruWidget33.dart';

/* Frame CRUD barang'
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCRUDbarangWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 10.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 460.0,
                child: GeneratedRectangle738Widget(),
              ),
              Positioned(
                left: 100.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 160.0,
                child: GeneratedRectangle663Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 30.0,
                child: GeneratedRectangle664Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 510.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 30.0,
                child: GeneratedRectangle669Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 140.0,
                child: GeneratedRectangle670Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 30.0,
                child: GeneratedRectangle665Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 30.0,
                child: GeneratedRectangle666Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 30.0,
                child: GeneratedRectangle667Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 30.0,
                child: GeneratedRectangle668Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 20.0,
                child: GeneratedToyotaAllNewAvanzaWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 23.0,
                child: Generated15Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 119.0,
                child:
                    GeneratedDeskripsiProdukDesainDasborPenuhBaruyangMencolokTipe15G3(),
              ),
              Positioned(
                left: 30.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 23.0,
                child: GeneratedToyotaWidget11(),
              ),
              Positioned(
                left: 30.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 20.0,
                child: GeneratedBlackMatteSilverWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 23.0,
                child: Generated2020Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 20.0,
                child: GeneratedMobilBaruWidget33(),
              ),
              Positioned(
                left: 40.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 30.0,
                child: GeneratedRectangle671Widget(),
              ),
              Positioned(
                left: 210.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 30.0,
                child: GeneratedRectangle672Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 21.0,
                child: GeneratedHapusWidget(),
              ),
              Positioned(
                left: 242.0,
                top: 737.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 21.0,
                child: GeneratedUnggahWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget26(),
              )
            ]),
      ),
    ));
  }
}
