import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedtambahalamatwidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/mobilapp/generatedtambahalamatwidget/generated/GeneratedAtaslogoWidget10.dart';
import 'package:flutterapp/mobilapp/generatedtambahalamatwidget/generated/GeneratedLine75Widget1.dart';
import 'package:flutterapp/mobilapp/generatedtambahalamatwidget/generated/GeneratedIconhomeWidget4.dart';
import 'package:flutterapp/mobilapp/generatedtambahalamatwidget/generated/GeneratedIconchatWidget7.dart';
import 'package:flutterapp/mobilapp/generatedtambahalamatwidget/generated/GeneratedRectangle734Widget.dart';
import 'package:flutterapp/mobilapp/generatedtambahalamatwidget/generated/GeneratedMOBILIKUWidget45.dart';

/* Frame tambah alamat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTambahalamatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 10.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 350.0,
                child: GeneratedRectangle734Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 428.0,
                child: GeneratedGroup18Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 1.0,
                child: GeneratedLine75Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget10(),
              ),
              Positioned(
                left: 23.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconhomeWidget4(),
              ),
              Positioned(
                left: 312.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconchatWidget7(),
              ),
              Positioned(
                left: 121.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget45(),
              )
            ]),
      ),
    ));
  }
}
