import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget/generated/GeneratedRectangle528Widget2.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget/generated/GeneratedNamalengkapWidget1.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget/generated/GeneratedMOBILIKUWidget36.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget/generated/GeneratedSegitigaWidget4.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget/generated/GeneratedNamalengkapWidget4.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget/generated/GeneratedNamalengkapWidget6.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget/generated/GeneratedNamalengkapWidget3.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget/generated/GeneratedNamalengkapWidget2.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget/generated/GeneratedNamalengkapWidget5.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget/generated/GeneratedKonfirmasibuttonWidget.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget/generated/GeneratedAtaslogoWidget1.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget/generated/GeneratedFotoWidget.dart';

/* Frame sign up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -173.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 483.1653747558594,
                height: 451.30841064453125,
                child: GeneratedSegitigaWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 300.0,
                child: GeneratedRectangle528Widget2(),
              ),
              Positioned(
                left: 115.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedFotoWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 30.0,
                child: GeneratedNamalengkapWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 30.0,
                child: GeneratedNamalengkapWidget2(),
              ),
              Positioned(
                left: 31.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 30.0,
                child: GeneratedNamalengkapWidget3(),
              ),
              Positioned(
                left: 30.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 30.0,
                child: GeneratedNamalengkapWidget4(),
              ),
              Positioned(
                left: 31.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 30.0,
                child: GeneratedNamalengkapWidget5(),
              ),
              Positioned(
                left: 30.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 30.0,
                child: GeneratedNamalengkapWidget6(),
              ),
              Positioned(
                left: 130.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedKonfirmasibuttonWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget1(),
              ),
              Positioned(
                left: 121.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget36(),
              )
            ]),
      ),
    ));
  }
}
