import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedProdukWidget25.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedLine34Widget8.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedProdukWidget23.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedFooterWidget14.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedProdukWidget20.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedProdukWidget21.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedLine35Widget10.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedLine36Widget12.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedAtaslogoWidget8.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedProdukWidget24.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedProdukWidget19.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedTitleWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget17/generated/GeneratedSegitigaWidget11.dart';

/* Frame Hot Sale
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHotSaleWidget17 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 910.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 910.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(10.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -157.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 483.1653747558594,
                              height: 451.30841064453125,
                              child: GeneratedSegitigaWidget11(),
                            ),
                            Positioned(
                              left: 126.0,
                              top: 60.0,
                              right: null,
                              bottom: null,
                              width: 113.0,
                              height: 60.0,
                              child: GeneratedTitleWidget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 150.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 199.0,
                              child: GeneratedProdukWidget19(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 200.0,
                              child: GeneratedProdukWidget20(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 610.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 199.0,
                              child: GeneratedProdukWidget21(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 610.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 199.0,
                              child: GeneratedProdukWidget23(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 200.0,
                              child: GeneratedProdukWidget24(),
                            ),
                            Positioned(
                              left: 190.0,
                              top: 150.0,
                              right: null,
                              bottom: null,
                              width: 155.0,
                              height: 199.0,
                              child: GeneratedProdukWidget25(),
                            ),
                            Positioned(
                              left: 180.507568359375,
                              top: 149.99961853027344,
                              right: null,
                              bottom: null,
                              width: 670.000732421875,
                              height: 1.0,
                              child: GeneratedLine34Widget8(),
                            ),
                            Positioned(
                              left: 9.99926471710205,
                              top: 361.5,
                              right: null,
                              bottom: null,
                              width: 340.00146484375,
                              height: 1.0,
                              child: GeneratedLine35Widget10(),
                            ),
                            Positioned(
                              left: 10.99926471710205,
                              top: 590.5,
                              right: null,
                              bottom: null,
                              width: 340.00146484375,
                              height: 1.0,
                              child: GeneratedLine36Widget12(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 50.0,
                              child: GeneratedAtaslogoWidget8(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 820.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 90.0,
                              child: GeneratedFooterWidget14(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
