import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedhomepagewidget/generated/GeneratedProdukjualanWidget10.dart';
import 'package:flutterapp/mobilapp/generatedhomepagewidget/generated/GeneratedRectangle171Widget.dart';
import 'package:flutterapp/mobilapp/generatedhomepagewidget/generated/GeneratedHomepageatasWidget.dart';
import 'package:flutterapp/mobilapp/generatedhomepagewidget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/mobilapp/generatedhomepagewidget/generated/GeneratedLine26Widget.dart';
import 'package:flutterapp/mobilapp/generatedhomepagewidget/generated/GeneratedBannertestimoniWidget.dart';
import 'package:flutterapp/mobilapp/generatedhomepagewidget/generated/GeneratedLine27Widget.dart';
import 'package:flutterapp/mobilapp/generatedhomepagewidget/generated/GeneratedLine28Widget.dart';
import 'package:flutterapp/mobilapp/generatedhomepagewidget/generated/GeneratedLogInWidget.dart';
import 'package:flutterapp/mobilapp/generatedhomepagewidget/generated/GeneratedLogomobilWidget.dart';
import 'package:flutterapp/mobilapp/generatedhomepagewidget/generated/GeneratedBanneratasWidget.dart';
import 'package:flutterapp/mobilapp/generatedhomepagewidget/generated/GeneratedBannerkatakataWidget.dart';

/* Frame Home Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2281.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 2281.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 240.0,
                              child: GeneratedHomepageatasWidget(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 280.0,
                              right: null,
                              bottom: null,
                              width: 1040.0,
                              height: 80.0,
                              child: GeneratedSearchWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 401.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 500.0,
                              child: GeneratedBanneratasWidget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 945.0,
                              right: null,
                              bottom: null,
                              width: 540.0,
                              height: 400.0,
                              child: GeneratedBannerkatakataWidget(),
                            ),
                            Positioned(
                              left: 700.0,
                              top: 945.0,
                              right: null,
                              bottom: null,
                              width: 660.0,
                              height: 700.0,
                              child: GeneratedBannertestimoniWidget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 1357.0,
                              right: null,
                              bottom: null,
                              width: 560.0,
                              height: 284.0,
                              child: GeneratedLogomobilWidget(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 1681.0,
                              right: null,
                              bottom: null,
                              width: 1360.0,
                              height: 299.0,
                              child: GeneratedProdukjualanWidget10(),
                            ),
                            Positioned(
                              left: 380.0,
                              top: 1700.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 1.0,
                              child: GeneratedLine26Widget(),
                            ),
                            Positioned(
                              left: 720.0,
                              top: 1700.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 1.0,
                              child: GeneratedLine27Widget(),
                            ),
                            Positioned(
                              left: 1080.0,
                              top: 1700.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 1.0,
                              child: GeneratedLine28Widget(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 67.0,
                              right: null,
                              bottom: null,
                              width: 162.0,
                              height: 60.0,
                              child: GeneratedRectangle171Widget(),
                            ),
                            Positioned(
                              left: 161.0,
                              top: 80.0,
                              right: null,
                              bottom: null,
                              width: 81.0,
                              height: 37.0,
                              child: GeneratedLogInWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
