import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedRectangle623Widget1.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedAtaslogoWidget21.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedJumlahyangharusdibayarWidget1.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedJumlahyangharusdibayarWidget.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedRp997000000Widget5.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedMOBILIKUWidget56.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedBayarSekarangWidget2.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedBMW330imsportWidget5.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedRp997000000Widget4.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedBayarSekarangWidget3.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedIconchatWidget16.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedRectangle625Widget1.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedBMW330imsportWidget4.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedIconhomeWidget14.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedRectangle624Widget1.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedBelumDibayarWidget.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedLine136Widget2.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedRectangle621Widget1.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedLine135Widget2.dart';
import 'package:flutterapp/mobilapp/generatedbelumdibayarwidget/generated/GeneratedFooterWidget18.dart';

/* Frame belum dibayar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBelumdibayarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 13.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 23.0,
                child: GeneratedBelumDibayarWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 90.0,
                child: GeneratedRectangle621Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 90.0,
                child: GeneratedRectangle624Widget1(),
              ),
              Positioned(
                left: 122.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 20.0,
                child: GeneratedBMW330imsportWidget4(),
              ),
              Positioned(
                left: 118.0,
                top: 222.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 20.0,
                child: GeneratedBMW330imsportWidget5(),
              ),
              Positioned(
                left: 123.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 15.0,
                child: GeneratedJumlahyangharusdibayarWidget(),
              ),
              Positioned(
                left: 119.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 15.0,
                child: GeneratedJumlahyangharusdibayarWidget1(),
              ),
              Positioned(
                left: 124.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 16.0,
                child: GeneratedRp997000000Widget4(),
              ),
              Positioned(
                left: 120.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 16.0,
                child: GeneratedRp997000000Widget5(),
              ),
              Positioned(
                left: 121.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 20.0,
                child: GeneratedRectangle623Widget1(),
              ),
              Positioned(
                left: 117.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 20.0,
                child: GeneratedRectangle625Widget1(),
              ),
              Positioned(
                left: 135.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 19.0,
                child: GeneratedBayarSekarangWidget2(),
              ),
              Positioned(
                left: 131.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 19.0,
                child: GeneratedBayarSekarangWidget3(),
              ),
              Positioned(
                left: 10.0,
                top: 205.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine135Widget2(),
              ),
              Positioned(
                left: 6.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine136Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget21(),
              ),
              Positioned(
                left: 23.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconhomeWidget14(),
              ),
              Positioned(
                left: 312.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconchatWidget16(),
              ),
              Positioned(
                left: 121.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget56(),
              ),
              Positioned(
                left: 0.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedFooterWidget18(),
              )
            ]),
      ),
    ));
  }
}
