import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedLine32Widget2.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedBanneratasWidget4.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedAtaslogoWidget6.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedFooterWidget12.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedProdukWidget10.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedLine31Widget3.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedKolomsearchWidget3.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedProdukWidget11.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedSegitigaWidget9.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedTopArrivalsWidget3.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedRectangle540Widget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedIconchatWidget3.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedProduktoparivalWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedProductWidget3.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedProduktoparrivalWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesesudahloginwidget1/generated/GeneratedLine33Widget6.dart';

/* Frame Home Page sesudah login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePagesesudahloginWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 870.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -157.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 483.1653747558594,
                height: 451.30841064453125,
                child: GeneratedSegitigaWidget9(),
              ),
              Positioned(
                left: 10.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 140.0,
                child: GeneratedBanneratasWidget4(),
              ),
              Positioned(
                left: 30.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 25.0,
                child: GeneratedKolomsearchWidget3(),
              ),
              Positioned(
                left: 10.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 18.0,
                child: GeneratedTopArrivalsWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 218.0,
                child: GeneratedProduktoparrivalWidget1(),
              ),
              Positioned(
                left: 200.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 218.0,
                child: GeneratedProduktoparivalWidget1(),
              ),
              Positioned(
                left: 180.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 1.0,
                child: GeneratedLine31Widget3(),
              ),
              Positioned(
                left: 180.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 1.0,
                child: GeneratedLine32Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 1.0,
                child: GeneratedLine33Widget6(),
              ),
              Positioned(
                left: 11.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 21.0,
                child: GeneratedProductWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 200.0,
                child: GeneratedProdukWidget10(),
              ),
              Positioned(
                left: 200.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedFooterWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget6(),
              ),
              Positioned(
                left: 307.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconchatWidget3(),
              ),
              Positioned(
                left: 21.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 25.0,
                child: GeneratedRectangle540Widget1(),
              )
            ]),
      ),
    ));
  }
}
