import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget/generated/GeneratedRectangle160Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget/generated/GeneratedLine33Widget3.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget/generated/GeneratedHomepageatasWidget6.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget/generated/GeneratedFooterWidget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget/generated/GeneratedProduk1Widget2.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget/generated/GeneratedLine34Widget5.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget/generated/GeneratedProduk2Widget2.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget/generated/GeneratedDaihatsuOfficialStoreWidget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget/generated/GeneratedEllipse8Widget.dart';

/* Frame Katalog Saya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKatalogSayaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1585.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1585.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 240.0,
                              child: GeneratedHomepageatasWidget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 320.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 220.0,
                              child: GeneratedRectangle160Widget(),
                            ),
                            Positioned(
                              left: 409.0,
                              top: 340.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 180.0,
                              child: GeneratedEllipse8Widget(),
                            ),
                            Positioned(
                              left: 627.0,
                              top: 404.0,
                              right: null,
                              bottom: null,
                              width: 405.0,
                              height: 55.0,
                              child: GeneratedDaihatsuOfficialStoreWidget(),
                            ),
                            Positioned(
                              left: 111.0,
                              top: 580.0,
                              right: null,
                              bottom: null,
                              width: 1218.0,
                              height: 292.0,
                              child: GeneratedProduk1Widget2(),
                            ),
                            Positioned(
                              left: 111.0,
                              top: 941.0,
                              right: null,
                              bottom: null,
                              width: 1200.0,
                              height: 292.0,
                              child: GeneratedProduk2Widget2(),
                            ),
                            Positioned(
                              left: 486.625,
                              top: 639.96728515625,
                              right: null,
                              bottom: null,
                              width: 660.0,
                              height: 1.0,
                              child: GeneratedLine33Widget3(),
                            ),
                            Positioned(
                              left: 940.533203125,
                              top: 639.9404296875,
                              right: null,
                              bottom: null,
                              width: 660.0,
                              height: 1.0,
                              child: GeneratedLine34Widget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1304.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 281.0,
                              child: GeneratedFooterWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
