import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedRp1107000000Widget.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedRp1077000000Widget.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedButtoncekoutWidget.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedKeranjangWidget19.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedRp131700000Widget1.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedRectangle531Widget8.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedBMWCoupeMSportWidget.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedTotalWidget4.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedProdukWidget27.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedSegitigaWidget12.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedMOBILIKUWidget44.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedAtaslogoWidget9.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedLine45Widget2.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedIconchatWidget6.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedRp131700000Widget2.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedIconhomeWidget3.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedProdukWidget28.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedLine44Widget2.dart';
import 'package:flutterapp/mobilapp/generatedkeranjangwidget18/generated/GeneratedProdukWidget26.dart';

/* Frame Keranjang
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKeranjangWidget18 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 121.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 20.0,
                child: GeneratedBMWCoupeMSportWidget(),
              ),
              Positioned(
                left: 113.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 23.0,
                child: GeneratedKeranjangWidget19(),
              ),
              Positioned(
                left: 20.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 90.0,
                child: GeneratedProdukWidget26(),
              ),
              Positioned(
                left: 20.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 90.0,
                child: GeneratedProdukWidget27(),
              ),
              Positioned(
                left: 20.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 276.0,
                child: GeneratedProdukWidget28(),
              ),
              Positioned(
                left: 10.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine44Widget2(),
              ),
              Positioned(
                left: 10.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine45Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedRectangle531Widget8(),
              ),
              Positioned(
                left: 20.0,
                top: 754.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 22.0,
                child: GeneratedTotalWidget4(),
              ),
              Positioned(
                left: 60.0,
                top: 754.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 22.0,
                child: GeneratedRp131700000Widget1(),
              ),
              Positioned(
                left: 210.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 70.0,
                child: GeneratedButtoncekoutWidget(),
              ),
              Positioned(
                left: 128.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 16.0,
                child: GeneratedRp131700000Widget2(),
              ),
              Positioned(
                left: 127.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 16.0,
                child: GeneratedRp1077000000Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 16.0,
                child: GeneratedRp1107000000Widget(),
              ),
              Positioned(
                left: -157.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 483.1653747558594,
                height: 451.30841064453125,
                child: GeneratedSegitigaWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget9(),
              ),
              Positioned(
                left: 23.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconhomeWidget3(),
              ),
              Positioned(
                left: 312.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconchatWidget6(),
              ),
              Positioned(
                left: 121.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget44(),
              )
            ]),
      ),
    ));
  }
}
