import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRp837000000Widget1.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRp830000000Widget1.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRectangle764Widget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedHeaderWidget7.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedBMW320iDynamiteWidget3.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRectangle765Widget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRp830000000Widget3.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedKonfirmasiHotSaleWidget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRectangle766Widget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedSetujuiWidget1.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRectangle769Widget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedBMW320iDynamiteWidget1.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRp830000000Widget4.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedBMW320iDynamiteWidget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRectangle758Widget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRp837000000Widget2.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedSetujuiWidget2.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRp837000000Widget4.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRectangle760Widget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedFooterWidget27.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedSetujuiWidget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRp837000000Widget3.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRectangle763Widget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedBMW320iDynamiteWidget2.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRp830000000Widget2.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRectangle762Widget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRectangle768Widget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedSetujuiWidget3.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRectangle761Widget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRectangle759Widget.dart';
import 'package:flutterapp/mobilapp/generatedkonfirmasihotsalewidget/generated/GeneratedRectangle767Widget.dart';

/* Frame konfirmasi hot sale
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKonfirmasihotsaleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 14.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 25.0,
                child: GeneratedKonfirmasiHotSaleWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 110.0,
                child: GeneratedRectangle758Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 110.0,
                child: GeneratedRectangle761Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 110.0,
                child: GeneratedRectangle764Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 110.0,
                child: GeneratedRectangle767Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedRectangle759Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedRectangle762Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedRectangle765Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedRectangle768Widget(),
              ),
              Positioned(
                left: 110.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 16.0,
                child: GeneratedBMW320iDynamiteWidget(),
              ),
              Positioned(
                left: 110.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 16.0,
                child: GeneratedBMW320iDynamiteWidget1(),
              ),
              Positioned(
                left: 110.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 16.0,
                child: GeneratedBMW320iDynamiteWidget2(),
              ),
              Positioned(
                left: 110.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 16.0,
                child: GeneratedBMW320iDynamiteWidget3(),
              ),
              Positioned(
                left: 230.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 16.0,
                child: GeneratedRp830000000Widget1(),
              ),
              Positioned(
                left: 230.0,
                top: 283.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 16.0,
                child: GeneratedRp830000000Widget2(),
              ),
              Positioned(
                left: 230.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 16.0,
                child: GeneratedRp830000000Widget3(),
              ),
              Positioned(
                left: 230.0,
                top: 543.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 16.0,
                child: GeneratedRp830000000Widget4(),
              ),
              Positioned(
                left: 110.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 16.0,
                child: GeneratedRp837000000Widget1(),
              ),
              Positioned(
                left: 110.0,
                top: 283.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 16.0,
                child: GeneratedRp837000000Widget2(),
              ),
              Positioned(
                left: 110.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 16.0,
                child: GeneratedRp837000000Widget3(),
              ),
              Positioned(
                left: 110.0,
                top: 543.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 16.0,
                child: GeneratedRp837000000Widget4(),
              ),
              Positioned(
                left: 240.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle760Widget(),
              ),
              Positioned(
                left: 240.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle763Widget(),
              ),
              Positioned(
                left: 240.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle766Widget(),
              ),
              Positioned(
                left: 240.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 20.0,
                child: GeneratedRectangle769Widget(),
              ),
              Positioned(
                left: 267.0,
                top: 183.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 19.0,
                child: GeneratedSetujuiWidget(),
              ),
              Positioned(
                left: 267.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 19.0,
                child: GeneratedSetujuiWidget1(),
              ),
              Positioned(
                left: 267.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 19.0,
                child: GeneratedSetujuiWidget2(),
              ),
              Positioned(
                left: 267.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 19.0,
                child: GeneratedSetujuiWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedHeaderWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedFooterWidget27(),
              )
            ]),
      ),
    ));
  }
}
