import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedMOBILIKUWidget54.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedDaihatsuSigraWidget2.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedBMW520iMSportWidget1.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedWishlistWidget23.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedProdukWidget39.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedProdukWidget38.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedFooterWidget16.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedRp131700000Widget3.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedIconhomeWidget13.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedBMWCoupeMSportWidget1.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedAtaslogoWidget19.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedIconchatWidget14.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedLine45Widget3.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedRp1077000000Widget1.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedProdukWidget37.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedRp1107000000Widget1.dart';
import 'package:flutterapp/mobilapp/generatedwishlistwidget22/generated/GeneratedLine44Widget3.dart';

/* Frame wish list
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWishlistWidget22 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 128.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 23.0,
                child: GeneratedWishlistWidget23(),
              ),
              Positioned(
                left: 121.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 20.0,
                child: GeneratedDaihatsuSigraWidget2(),
              ),
              Positioned(
                left: 121.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 20.0,
                child: GeneratedBMW520iMSportWidget1(),
              ),
              Positioned(
                left: 121.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 20.0,
                child: GeneratedBMWCoupeMSportWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 320.5504455566406,
                height: 90.0,
                child: GeneratedProdukWidget37(),
              ),
              Positioned(
                left: 20.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 320.5504455566406,
                height: 90.0,
                child: GeneratedProdukWidget38(),
              ),
              Positioned(
                left: 20.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 320.5504455566406,
                height: 276.0,
                child: GeneratedProdukWidget39(),
              ),
              Positioned(
                left: 10.0,
                top: 211.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine44Widget3(),
              ),
              Positioned(
                left: 10.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine45Widget3(),
              ),
              Positioned(
                left: 128.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 16.0,
                child: GeneratedRp131700000Widget3(),
              ),
              Positioned(
                left: 127.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 16.0,
                child: GeneratedRp1077000000Widget1(),
              ),
              Positioned(
                left: 127.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 16.0,
                child: GeneratedRp1107000000Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget19(),
              ),
              Positioned(
                left: 23.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconhomeWidget13(),
              ),
              Positioned(
                left: 312.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconchatWidget14(),
              ),
              Positioned(
                left: 121.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget54(),
              ),
              Positioned(
                left: 0.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedFooterWidget16(),
              )
            ]),
      ),
    ));
  }
}
