import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedRectangle620Widget.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedDetailprofileWidget5.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedDetailprofileWidget4.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedKonfirmasiWidget4.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedDetailprofileWidget2.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedIconhomeWidget12.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedMOBILIKUWidget53.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedDetailprofileWidget1.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedDetailprofileWidget3.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedDetailprofileWidget.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedDetailprofileWidget6.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedRectangle619Widget.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedEllipse104Widget.dart';
import 'package:flutterapp/mobilapp/generatededitprofilwidget/generated/GeneratedAtaslogoWidget18.dart';

/* Frame edit profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEditprofilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 10.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 510.0,
                child: GeneratedRectangle620Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 231.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedDetailprofileWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedDetailprofileWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedDetailprofileWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedDetailprofileWidget3(),
              ),
              Positioned(
                left: 30.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedDetailprofileWidget4(),
              ),
              Positioned(
                left: 30.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 40.0,
                child: GeneratedDetailprofileWidget5(),
              ),
              Positioned(
                left: 30.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 110.0,
                child: GeneratedDetailprofileWidget6(),
              ),
              Positioned(
                left: 250.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle619Widget(),
              ),
              Positioned(
                left: 259.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 23.0,
                child: GeneratedKonfirmasiWidget4(),
              ),
              Positioned(
                left: 120.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 120.0,
                child: GeneratedEllipse104Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget18(),
              ),
              Positioned(
                left: 23.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconhomeWidget12(),
              ),
              Positioned(
                left: 121.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget53(),
              )
            ]),
      ),
    ));
  }
}
