import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedaddalamatwidget/generated/GeneratedLine74Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddalamatwidget/generated/GeneratedRectangle596Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddalamatwidget/generated/GeneratedAlamatpengirimanWidget.dart';
import 'package:flutterapp/mobilapp/generatedaddalamatwidget/generated/GeneratedRectangle574Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddalamatwidget/generated/GeneratedAlamatpengirimanWidget1.dart';
import 'package:flutterapp/mobilapp/generatedaddalamatwidget/generated/GeneratedTambahWidget.dart';
import 'package:flutterapp/mobilapp/generatedaddalamatwidget/generated/GeneratedPilihalamatpengirimanWidget.dart';
import 'package:flutterapp/mobilapp/generatedaddalamatwidget/generated/GeneratedLine71Widget.dart';

/* Frame add alamat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddalamatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 320.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 280.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 20.0,
                child: GeneratedRectangle596Widget(),
              ),
              Positioned(
                left: 296.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 16.0,
                child: GeneratedTambahWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 177.0,
                height: 21.0,
                child: GeneratedPilihalamatpengirimanWidget(),
              ),
              Positioned(
                left: 285.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedRectangle574Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 40.0,
                right: null,
                bottom: null,
                width: 340.00146484375,
                height: 1.0,
                child: GeneratedLine71Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 111.0,
                child: GeneratedAlamatpengirimanWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 111.0,
                child: GeneratedAlamatpengirimanWidget1(),
              ),
              Positioned(
                left: 10.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine74Widget(),
              )
            ]),
      ),
    ));
  }
}
