import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedpesananmasukwidget/generated/GeneratedTerimaWidget.dart';
import 'package:flutterapp/mobilapp/generatedpesananmasukwidget/generated/GeneratedRectangle161Widget.dart';
import 'package:flutterapp/mobilapp/generatedpesananmasukwidget/generated/GeneratedTolakWidget.dart';
import 'package:flutterapp/mobilapp/generatedpesananmasukwidget/generated/GeneratedPesananMasukWidget1.dart';
import 'package:flutterapp/mobilapp/generatedpesananmasukwidget/generated/GeneratedAtasWidget14.dart';
import 'package:flutterapp/mobilapp/generatedpesananmasukwidget/generated/GeneratedRectangle162Widget.dart';
import 'package:flutterapp/mobilapp/generatedpesananmasukwidget/generated/GeneratedProdukWidget5.dart';

/* Frame Pesanan Masuk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPesananMasukWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 200.0,
                              child: GeneratedAtasWidget14(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 225.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 68.0,
                              child: GeneratedPesananMasukWidget1(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 1360.0,
                              height: 362.0,
                              child: GeneratedProdukWidget5(),
                            ),
                            Positioned(
                              left: 902.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 218.0,
                              height: 80.0,
                              child: GeneratedRectangle161Widget(),
                            ),
                            Positioned(
                              left: 1162.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 218.0,
                              height: 80.0,
                              child: GeneratedRectangle162Widget(),
                            ),
                            Positioned(
                              left: 945.0,
                              top: 654.0,
                              right: null,
                              bottom: null,
                              width: 130.0,
                              height: 58.0,
                              child: GeneratedTerimaWidget(),
                            ),
                            Positioned(
                              left: 1220.0,
                              top: 654.0,
                              right: null,
                              bottom: null,
                              width: 99.0,
                              height: 58.0,
                              child: GeneratedTolakWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
