import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget1/generated/GeneratedHomepageatasWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget1/generated/GeneratedBaris5Widget.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget1/generated/GeneratedLine32Widget.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget1/generated/GeneratedHotSaleWidget3.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget1/generated/Generated090151Widget.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget1/generated/GeneratedBaris1Widget.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget1/generated/GeneratedProdukterlarisWidget.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget1/generated/GeneratedLine31Widget1.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget1/generated/GeneratedBaris4Widget.dart';

/* Frame Hot Sale
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHotSaleWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2380.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 2380.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 240.0,
                              child: GeneratedHomepageatasWidget1(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 286.0,
                              right: null,
                              bottom: null,
                              width: 182.0,
                              height: 68.0,
                              child: GeneratedHotSaleWidget3(),
                            ),
                            Positioned(
                              left: 1120.0,
                              top: 286.0,
                              right: null,
                              bottom: null,
                              width: 236.0,
                              height: 68.0,
                              child: Generated090151Widget(),
                            ),
                            Positioned(
                              left: 380.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 680.0,
                              height: 580.0,
                              child: GeneratedProdukterlarisWidget(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 1040.0,
                              right: null,
                              bottom: null,
                              width: 1200.0,
                              height: 301.0,
                              child: GeneratedBaris1Widget(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 1399.0,
                              right: null,
                              bottom: null,
                              width: 1200.0,
                              height: 301.0,
                              child: GeneratedBaris4Widget(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 1758.0,
                              right: null,
                              bottom: null,
                              width: 1200.0,
                              height: 301.0,
                              child: GeneratedBaris5Widget(),
                            ),
                            Positioned(
                              left: 488.0,
                              top: 1040.0,
                              right: null,
                              bottom: null,
                              width: 1043.0042724609375,
                              height: 1.0,
                              child: GeneratedLine31Widget1(),
                            ),
                            Positioned(
                              left: 949.0,
                              top: 1040.0,
                              right: null,
                              bottom: null,
                              width: 1043.0042724609375,
                              height: 1.0,
                              child: GeneratedLine32Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
