import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget3/generated/GeneratedProduk2Widget1.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget3/generated/GeneratedProduk1Widget1.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget3/generated/GeneratedProduk4Widget1.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget3/generated/GeneratedProduk3Widget1.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget3/generated/GeneratedHomepageatasWidget3.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget3/generated/GeneratedMobilBekasWidget5.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget3/generated/GeneratedLine33Widget1.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget3/generated/GeneratedLine34Widget3.dart';

/* Frame Mobil Bekas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMobilBekasWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2064.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 2064.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 240.0,
                              child: GeneratedHomepageatasWidget3(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 1218.0,
                              height: 292.0,
                              child: GeneratedProduk1Widget1(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 741.0,
                              right: null,
                              bottom: null,
                              width: 1200.0,
                              height: 292.0,
                              child: GeneratedProduk2Widget1(),
                            ),
                            Positioned(
                              left: 122.0,
                              top: 1101.0,
                              right: null,
                              bottom: null,
                              width: 1200.0,
                              height: 292.0,
                              child: GeneratedProduk3Widget1(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 1460.0,
                              right: null,
                              bottom: null,
                              width: 1200.0,
                              height: 292.0,
                              child: GeneratedProduk4Widget1(),
                            ),
                            Positioned(
                              left: 586.0,
                              top: 264.0,
                              right: null,
                              bottom: null,
                              width: 271.0,
                              height: 68.0,
                              child: GeneratedMobilBekasWidget5(),
                            ),
                            Positioned(
                              left: 489.25,
                              top: 439.9996337890625,
                              right: null,
                              bottom: null,
                              width: 1320.0,
                              height: 1.0,
                              child: GeneratedLine33Widget1(),
                            ),
                            Positioned(
                              left: 950.0,
                              top: 439.94061279296875,
                              right: null,
                              bottom: null,
                              width: 1320.0,
                              height: 1.0,
                              child: GeneratedLine34Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
