import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget/generated/GeneratedChatpenggunaWidget6.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget/generated/GeneratedChatpenggunaWidget5.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget/generated/GeneratedLogoWidget2.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget/generated/GeneratedChatpenggunaWidget4.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget/generated/GeneratedAtasWidget2.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget/generated/GeneratedChatpenggunaWidget3.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget/generated/GeneratedChatpenggunaWidget2.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget/generated/GeneratedChatpenggunaWidget7.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget/generated/GeneratedChatpenggunaWidget1.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget/generated/GeneratedChatpenggunaWidget.dart';

/* Frame chat 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChat1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2000.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 2000.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.036376953125,
                              height: 160.0,
                              child: GeneratedAtasWidget2(),
                            ),
                            Positioned(
                              left: 541.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 360.0000305175781,
                              height: 120.0,
                              child: GeneratedLogoWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 200.0,
                              right: null,
                              bottom: null,
                              width: 1380.0,
                              height: 180.0,
                              child: GeneratedChatpenggunaWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 1380.0,
                              height: 180.0,
                              child: GeneratedChatpenggunaWidget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 600.0,
                              right: null,
                              bottom: null,
                              width: 1380.0,
                              height: 180.0,
                              child: GeneratedChatpenggunaWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 1380.0,
                              height: 180.0,
                              child: GeneratedChatpenggunaWidget3(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1000.0,
                              right: null,
                              bottom: null,
                              width: 1380.0,
                              height: 180.0,
                              child: GeneratedChatpenggunaWidget4(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1200.0,
                              right: null,
                              bottom: null,
                              width: 1380.0,
                              height: 180.0,
                              child: GeneratedChatpenggunaWidget5(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1400.0,
                              right: null,
                              bottom: null,
                              width: 1380.0,
                              height: 180.0,
                              child: GeneratedChatpenggunaWidget6(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 1600.0,
                              right: null,
                              bottom: null,
                              width: 1380.0,
                              height: 180.0,
                              child: GeneratedChatpenggunaWidget7(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
