import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generateddesktop7widget/generated/GeneratedNumber10Widget.dart';
import 'package:flutterapp/mobilapp/generateddesktop7widget/generated/GeneratedNumber9Widget.dart';
import 'package:flutterapp/mobilapp/generateddesktop7widget/generated/GeneratedNumber3Widget.dart';
import 'package:flutterapp/mobilapp/generateddesktop7widget/generated/GeneratedNumber8Widget.dart';
import 'package:flutterapp/mobilapp/generateddesktop7widget/generated/GeneratedNumber5Widget.dart';
import 'package:flutterapp/mobilapp/generateddesktop7widget/generated/GeneratedNumber1Widget1.dart';
import 'package:flutterapp/mobilapp/generateddesktop7widget/generated/GeneratedNumber7Widget.dart';
import 'package:flutterapp/mobilapp/generateddesktop7widget/generated/GeneratedNumber4Widget.dart';
import 'package:flutterapp/mobilapp/generateddesktop7widget/generated/GeneratedNumber2Widget1.dart';
import 'package:flutterapp/mobilapp/generateddesktop7widget/generated/GeneratedNumber6Widget.dart';

/* Frame Desktop - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedNumber1Widget1(),
                            ),
                            Positioned(
                              left: 260.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedNumber2Widget1(),
                            ),
                            Positioned(
                              left: 180.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedNumber3Widget(),
                            ),
                            Positioned(
                              left: 100.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedNumber4Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 100.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedNumber5Widget(),
                            ),
                            Positioned(
                              left: 420.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedNumber6Widget(),
                            ),
                            Positioned(
                              left: 340.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedNumber7Widget(),
                            ),
                            Positioned(
                              left: 260.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedNumber8Widget(),
                            ),
                            Positioned(
                              left: 180.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedNumber9Widget(),
                            ),
                            Positioned(
                              left: 100.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedNumber10Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
