import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedRectangle561Widget2.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedPengaturanWidget16.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedEditWidget.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedHargaWidget14.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedRectangle558Widget2.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedRectangle556Widget2.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedMerkWidget4.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedTerapkanWidget2.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedMobilBaruWidget34.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedRectangle559Widget2.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedRectangle560Widget2.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedRectangle562Widget.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedMobilBekasWidget33.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedRectangle555Widget2.dart';
import 'package:flutterapp/mobilapp/generatedpengaturanadminwidget/generated/GeneratedRectangle557Widget2.dart';

/* Frame Pengaturan  admin
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPengaturanadminWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 249.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 62, 73, 122),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 800.0,
                child: GeneratedRectangle555Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 25.0,
                child: GeneratedPengaturanWidget16(),
              ),
              Positioned(
                left: 20.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 30.0,
                child: GeneratedRectangle556Widget2(),
              ),
              Positioned(
                left: 28.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 20.0,
                child: GeneratedMobilBaruWidget34(),
              ),
              Positioned(
                left: 20.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedRectangle557Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedRectangle558Widget2(),
              ),
              Positioned(
                left: 133.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 30.0,
                child: GeneratedRectangle559Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 30.0,
                child: GeneratedRectangle560Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedRectangle561Widget2(),
              ),
              Positioned(
                left: 133.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedRectangle562Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 24.0,
                child: GeneratedTerapkanWidget2(),
              ),
              Positioned(
                left: 170.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 24.0,
                child: GeneratedEditWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 20.0,
                child: GeneratedMobilBekasWidget33(),
              ),
              Positioned(
                left: 28.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 23.0,
                child: GeneratedMerkWidget4(),
              ),
              Positioned(
                left: 27.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 23.0,
                child: GeneratedHargaWidget14(),
              ),
              Positioned(
                left: 121.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 31.0,
                child: GeneratedWidget2(),
              )
            ]),
      ),
    ));
  }
}
