import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget1/generated/GeneratedKonfirmasibuttonWidget1.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget1/generated/GeneratedRectangle528Widget3.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget1/generated/GeneratedAtaslogoWidget2.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget1/generated/GeneratedSegitigaWidget5.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget1/generated/GeneratedFotoWidget1.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget1/generated/GeneratedMOBILIKUWidget37.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget1/generated/GeneratedNamalengkapWidget9.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget1/generated/GeneratedNamalengkapWidget8.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget1/generated/GeneratedNamalengkapWidget11.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget1/generated/GeneratedNamalengkapWidget12.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget1/generated/GeneratedNamalengkapWidget10.dart';
import 'package:flutterapp/mobilapp/generatedsignupwidget1/generated/GeneratedNamalengkapWidget7.dart';

/* Frame sign up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -173.0,
                top: 267.0,
                right: null,
                bottom: null,
                width: 483.1653747558594,
                height: 451.30841064453125,
                child: GeneratedSegitigaWidget5(),
              ),
              Positioned(
                left: 20.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 300.0,
                child: GeneratedRectangle528Widget3(),
              ),
              Positioned(
                left: 115.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 130.0,
                child: GeneratedFotoWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 30.0,
                child: GeneratedNamalengkapWidget7(),
              ),
              Positioned(
                left: 31.0,
                top: 290.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 30.0,
                child: GeneratedNamalengkapWidget8(),
              ),
              Positioned(
                left: 31.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 30.0,
                child: GeneratedNamalengkapWidget9(),
              ),
              Positioned(
                left: 30.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 30.0,
                child: GeneratedNamalengkapWidget10(),
              ),
              Positioned(
                left: 31.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 30.0,
                child: GeneratedNamalengkapWidget11(),
              ),
              Positioned(
                left: 30.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 30.0,
                child: GeneratedNamalengkapWidget12(),
              ),
              Positioned(
                left: 130.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 30.0,
                child: GeneratedKonfirmasibuttonWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget2(),
              ),
              Positioned(
                left: 121.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget37(),
              )
            ]),
      ),
    ));
  }
}
