import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedreqhotsalewidget/generated/GeneratedFooterWidget22.dart';
import 'package:flutterapp/mobilapp/generatedreqhotsalewidget/generated/GeneratedRectangle731Widget1.dart';
import 'package:flutterapp/mobilapp/generatedreqhotsalewidget/generated/GeneratedKirimWidget1.dart';
import 'package:flutterapp/mobilapp/generatedreqhotsalewidget/generated/GeneratedBMW320iDynamicWidget.dart';
import 'package:flutterapp/mobilapp/generatedreqhotsalewidget/generated/GeneratedHeaderWidget1.dart';
import 'package:flutterapp/mobilapp/generatedreqhotsalewidget/generated/GeneratedRectangle734Widget1.dart';
import 'package:flutterapp/mobilapp/generatedreqhotsalewidget/generated/GeneratedRectangle732Widget1.dart';
import 'package:flutterapp/mobilapp/generatedreqhotsalewidget/generated/GeneratedRectangle733Widget1.dart';
import 'package:flutterapp/mobilapp/generatedreqhotsalewidget/generated/GeneratedRectangle735Widget1.dart';
import 'package:flutterapp/mobilapp/generatedreqhotsalewidget/generated/GeneratedRp830000000Widget.dart';
import 'package:flutterapp/mobilapp/generatedreqhotsalewidget/generated/GeneratedRectangle730Widget7.dart';
import 'package:flutterapp/mobilapp/generatedreqhotsalewidget/generated/GeneratedRp837000000Widget.dart';

/* Frame req hot sale
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReqhotsaleWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 100.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 160.0,
                child: GeneratedRectangle730Widget7(),
              ),
              Positioned(
                left: 20.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 150.0,
                child: GeneratedRectangle731Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle732Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle735Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 20.0,
                child: GeneratedRp837000000Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 20.0,
                child: GeneratedBMW320iDynamicWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 30.0,
                child: GeneratedRectangle733Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 20.0,
                child: GeneratedRp830000000Widget(),
              ),
              Positioned(
                left: 115.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 30.0,
                child: GeneratedRectangle734Widget1(),
              ),
              Positioned(
                left: 160.0,
                top: 435.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 25.0,
                child: GeneratedKirimWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedHeaderWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedFooterWidget22(),
              )
            ]),
      ),
    ));
  }
}
