import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedPutihWidget.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedFaridaWidget2.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/Generated1ProdukWidget1.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedRectangle563Widget.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedMOBILIKUWidget75.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedSegitigaWidget13.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedDaihatsuSigraWidget3.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedDelivertoWidget.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedMobilBaruWidget46.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedRectangle564Widget.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedIconhomeWidget28.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedIconchatWidget32.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedOrderdetailsWidget.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedRectangle568Widget.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedButtonkonfirmWidget.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedMetodeWidget.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedRectangle594Widget1.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedRectangle562Widget1.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedRectangle567Widget.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedDetailProdukWidget.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedAtaslogoWidget40.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedRectangle569Widget.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedRectangle565Widget.dart';
import 'package:flutterapp/mobilapp/generatedcheckoutwidget/generated/GeneratedJlManggisD101Rt02Rw03Widget.dart';

/* Frame check out
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckoutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 881.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -157.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 483.1653747558594,
                height: 451.30841064453125,
                child: GeneratedSegitigaWidget13(),
              ),
              Positioned(
                left: 19.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 26.0,
                child: GeneratedDelivertoWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 90.0,
                child: GeneratedRectangle562Widget1(),
              ),
              Positioned(
                left: 290.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedRectangle563Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 310.0,
                child: GeneratedRectangle564Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 320.0000305175781,
                height: 130.0,
                child: GeneratedOrderdetailsWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 24.0,
                child: GeneratedDetailProdukWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 90.0,
                child: GeneratedRectangle565Widget(),
              ),
              Positioned(
                left: 140.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 10.0,
                child: GeneratedRectangle567Widget(),
              ),
              Positioned(
                left: 140.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 10.0,
                child: GeneratedRectangle568Widget(),
              ),
              Positioned(
                left: 140.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 10.0,
                child: GeneratedRectangle569Widget(),
              ),
              Positioned(
                left: 147.0,
                top: 309.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 13.0,
                child: Generated1ProdukWidget1(),
              ),
              Positioned(
                left: 155.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 16.0,
                child: GeneratedPutihWidget(),
              ),
              Positioned(
                left: 143.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 13.0,
                child: GeneratedMobilBaruWidget46(),
              ),
              Positioned(
                left: 110.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 40.0,
                child: GeneratedButtonkonfirmWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 173.0,
                height: 30.0,
                child: GeneratedFaridaWidget2(),
              ),
              Positioned(
                left: 42.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 242.0,
                height: 22.0,
                child: GeneratedJlManggisD101Rt02Rw03Widget(),
              ),
              Positioned(
                left: 320.0002746582031,
                top: 230.00048828125,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle594Widget1(),
              ),
              Positioned(
                left: 140.0,
                top: 282.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 20.0,
                child: GeneratedDaihatsuSigraWidget3(),
              ),
              Positioned(
                left: 10.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 240.0,
                child: GeneratedMetodeWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget40(),
              ),
              Positioned(
                left: 23.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconhomeWidget28(),
              ),
              Positioned(
                left: 312.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconchatWidget32(),
              ),
              Positioned(
                left: 121.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget75(),
              )
            ]),
      ),
    ));
  }
}
