import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedHyundaiWidget7.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedAkunWidget17.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedWishlistWidget14.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedMobilBaruWidget17.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedDaihatsuWidget7.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedHondaWidget7.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedInstagram1Widget7.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedBMWWidget7.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedPengaturanWidget8.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedMobilBekasWidget17.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedToyotaWidget7.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedWebsitepenjualanmobilterpecayaWidget7.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedKatalogsayaWidget6.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedMOBILIKUWidget27.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget7/generated/GeneratedRectangle172Widget7.dart';

/* Group footer
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFooterWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1440.0,
      height: 281.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 1440.0,
              height: 281.0,
              child: GeneratedRectangle172Widget7(),
            ),
            Positioned(
              left: 40.0,
              top: 46.0,
              right: null,
              bottom: null,
              width: 505.0,
              height: 91.0,
              child: GeneratedMOBILIKUWidget27(),
            ),
            Positioned(
              left: 1315.0,
              top: 200.0,
              right: null,
              bottom: null,
              width: 45.0,
              height: 45.0,
              child: GeneratedInstagram1Widget7(),
            ),
            Positioned(
              left: 720.0,
              top: 24.0,
              right: null,
              bottom: null,
              width: 105.0,
              height: 38.0,
              child: GeneratedMobilBaruWidget17(),
            ),
            Positioned(
              left: 720.0,
              top: 65.0,
              right: null,
              bottom: null,
              width: 86.0,
              height: 28.0,
              child: GeneratedDaihatsuWidget7(),
            ),
            Positioned(
              left: 1095.0,
              top: 65.0,
              right: null,
              bottom: null,
              width: 54.0,
              height: 28.0,
              child: GeneratedAkunWidget17(),
            ),
            Positioned(
              left: 720.0,
              top: 93.0,
              right: null,
              bottom: null,
              width: 66.0,
              height: 28.0,
              child: GeneratedToyotaWidget7(),
            ),
            Positioned(
              left: 1095.0,
              top: 121.0,
              right: null,
              bottom: null,
              width: 115.0,
              height: 25.0,
              child: GeneratedKatalogsayaWidget6(),
            ),
            Positioned(
              left: 1095.0,
              top: 93.0,
              right: null,
              bottom: null,
              width: 79.0,
              height: 28.0,
              child: GeneratedWishlistWidget14(),
            ),
            Positioned(
              left: 721.0,
              top: 121.0,
              right: null,
              bottom: null,
              width: 54.0,
              height: 28.0,
              child: GeneratedBMWWidget7(),
            ),
            Positioned(
              left: 720.0,
              top: 149.0,
              right: null,
              bottom: null,
              width: 64.0,
              height: 28.0,
              child: GeneratedHondaWidget7(),
            ),
            Positioned(
              left: 720.0,
              top: 177.0,
              right: null,
              bottom: null,
              width: 83.0,
              height: 28.0,
              child: GeneratedHyundaiWidget7(),
            ),
            Positioned(
              left: 900.0,
              top: 24.0,
              right: null,
              bottom: null,
              width: 120.0,
              height: 38.0,
              child: GeneratedMobilBekasWidget17(),
            ),
            Positioned(
              left: 1095.0,
              top: 20.0,
              right: null,
              bottom: null,
              width: 115.0,
              height: 41.0,
              child: GeneratedPengaturanWidget8(),
            ),
            Positioned(
              left: 119.0,
              top: 149.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 28.0,
              child: GeneratedWebsitepenjualanmobilterpecayaWidget7(),
            )
          ]),
    ));
  }
}
