import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget2/generated/GeneratedProdukWidget58.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget2/generated/GeneratedProdukWidget62.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget2/generated/GeneratedHeaderWidget4.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget2/generated/GeneratedMobilBekasWidget39.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget2/generated/GeneratedLine221Widget3.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget2/generated/GeneratedProdukWidget59.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget2/generated/GeneratedProdukWidget60.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget2/generated/GeneratedLine222Widget3.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget2/generated/GeneratedLine220Widget3.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget2/generated/GeneratedFooterWidget25.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget2/generated/GeneratedProdukWidget63.dart';
import 'package:flutterapp/mobilapp/generatedmobilbekaswidget2/generated/GeneratedProdukWidget61.dart';

/* Frame mobil bekas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMobilbekasWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 850.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 99.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 20.0,
                child: GeneratedMobilBekasWidget39(),
              ),
              Positioned(
                left: 10.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 200.0,
                child: GeneratedProdukWidget58(),
              ),
              Positioned(
                left: 10.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 200.0,
                child: GeneratedProdukWidget59(),
              ),
              Positioned(
                left: 10.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 200.0,
                child: GeneratedProdukWidget60(),
              ),
              Positioned(
                left: 200.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget61(),
              ),
              Positioned(
                left: 200.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget62(),
              ),
              Positioned(
                left: 200.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget63(),
              ),
              Positioned(
                left: 180.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 645.0,
                height: 1.0,
                child: GeneratedLine220Widget3(),
              ),
              Positioned(
                left: 10.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine221Widget3(),
              ),
              Positioned(
                left: 10.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine222Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedHeaderWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedFooterWidget25(),
              )
            ]),
      ),
    ));
  }
}
