import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedUntukstokwarnablackmattenyasedangkosongkakkamijugaadawa.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedPesanansudahkamikirimyakakmohonditunnguWidget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedLine213Widget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedEllipse14Widget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedNumber2Widget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedEllipse13Widget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedNumber1Widget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedAtasWidget22.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedHaiminUntukpembayaranapabisamenggunakanmetodelainaWidge.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedLine211Widget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedRayWidget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedUntukstokwarnablackmattenyasedangkosongkakkamijugaadawa1.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedIndiraWidget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedViaWidget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedLine210Widget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedJansenWidget.dart';
import 'package:flutterapp/mobilapp/generatedchat1widget1/generated/GeneratedLine212Widget.dart';

/* Frame chat 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChat1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2000.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 2000.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 200.0,
                              child: GeneratedAtasWidget22(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 240.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 154.0,
                              child: GeneratedEllipse11Widget(),
                            ),
                            Positioned(
                              left: 249.0,
                              top: 260.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 58.0,
                              child: GeneratedViaWidget(),
                            ),
                            Positioned(
                              left: 249.0,
                              top: 320.0,
                              right: null,
                              bottom: null,
                              width: 660.0,
                              height: 37.0,
                              child:
                                  GeneratedPesanansudahkamikirimyakakmohonditunnguWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 420.0,
                              right: null,
                              bottom: null,
                              width: 1360.0,
                              height: 1.0,
                              child: GeneratedLine210Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 154.0,
                              child: GeneratedEllipse13Widget(),
                            ),
                            Positioned(
                              left: 249.0,
                              top: 660.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 58.0,
                              child: GeneratedJansenWidget(),
                            ),
                            Positioned(
                              left: 249.0,
                              top: 720.0,
                              right: null,
                              bottom: null,
                              width: 852.0,
                              height: 37.0,
                              child:
                                  GeneratedHaiminUntukpembayaranapabisamenggunakanmetodelainaWidge(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 820.0,
                              right: null,
                              bottom: null,
                              width: 1360.0,
                              height: 1.0,
                              child: GeneratedLine212Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 440.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 154.0,
                              child: GeneratedEllipse12Widget(),
                            ),
                            Positioned(
                              left: 249.0,
                              top: 460.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 58.0,
                              child: GeneratedIndiraWidget(),
                            ),
                            Positioned(
                              left: 249.0,
                              top: 520.0,
                              right: null,
                              bottom: null,
                              width: 1103.0,
                              height: 37.0,
                              child:
                                  GeneratedUntukstokwarnablackmattenyasedangkosongkakkamijugaadawa(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 620.0,
                              right: null,
                              bottom: null,
                              width: 1360.0,
                              height: 1.0,
                              child: GeneratedLine211Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 154.0,
                              child: GeneratedEllipse14Widget(),
                            ),
                            Positioned(
                              left: 249.0,
                              top: 860.0,
                              right: null,
                              bottom: null,
                              width: 73.0,
                              height: 58.0,
                              child: GeneratedRayWidget(),
                            ),
                            Positioned(
                              left: 249.0,
                              top: 920.0,
                              right: null,
                              bottom: null,
                              width: 1091.0,
                              height: 37.0,
                              child:
                                  GeneratedUntukstokwarnablackmattenyasedangkosongkakkamijugaadawa1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 1020.0,
                              right: null,
                              bottom: null,
                              width: 1360.0,
                              height: 1.0,
                              child: GeneratedLine213Widget(),
                            ),
                            Positioned(
                              left: 1340.0,
                              top: 687.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedNumber1Widget(),
                            ),
                            Positioned(
                              left: 1340.0,
                              top: 880.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedNumber2Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
