import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedMOBILIKUWidget35.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedRectangle525Widget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedRectangle524Widget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedIconwishlistWidget5.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/Generated475Widget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedLine30Widget3.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedIconhotsaleWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedIconwishlistWidget7.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedBanneratasWidget2.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedKiaPicantoWidget3.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/Generated485Widget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedLine28Widget3.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedIconmobilbekasWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedBMW430icoupemsportproWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedIconpengaturanWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedLine28Widget4.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedProductWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedButtonloginWidget.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedLine29Widget2.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedHyundaiCretaWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedSegitigaWidget3.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedStar1Widget2.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedStar2Widget2.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedRp1357000000Widget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedRectangle523Widget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedRp592350000Widget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedRp293000000Widget2.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedKolomsearchWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedRp110000000Widget5.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedRectangle522Widget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedIconwishlistWidget6.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedHondaCivicWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedIconwishlistWidget4.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedSegitigaWidget2.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedIconmobilbaruWidget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedRectangle528Widget1.dart';
import 'package:flutterapp/mobilapp/generatedhomepagesebelumloginwidget1/generated/GeneratedTopArrivalsWidget1.dart';

/* Frame Home page sebelum Log In
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomepagesebelumLogInWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 892.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 340.31549072265625,
                top: 520.0,
                right: null,
                bottom: null,
                width: 483.1653747558594,
                height: 451.30841064453125,
                child: GeneratedSegitigaWidget2(),
              ),
              Positioned(
                left: -143.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 483.1653747558594,
                height: 451.30841064453125,
                child: GeneratedSegitigaWidget3(),
              ),
              Positioned(
                left: 10.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 18.0,
                child: GeneratedTopArrivalsWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 140.0,
                child: GeneratedRectangle522Widget1(),
              ),
              Positioned(
                left: 200.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 140.0,
                child: GeneratedRectangle523Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 26.0,
                child: GeneratedBMW430icoupemsportproWidget1(),
              ),
              Positioned(
                left: 203.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 18.0,
                child: GeneratedHondaCivicWidget1(),
              ),
              Positioned(
                left: 200.0,
                top: 767.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 18.0,
                child: GeneratedHyundaiCretaWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 767.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 18.0,
                child: GeneratedKiaPicantoWidget3(),
              ),
              Positioned(
                left: 23.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 18.0,
                child: GeneratedRp1357000000Widget1(),
              ),
              Positioned(
                left: 203.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 18.0,
                child: GeneratedRp592350000Widget1(),
              ),
              Positioned(
                left: 200.0,
                top: 797.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 18.0,
                child: GeneratedRp293000000Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 797.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 18.0,
                child: GeneratedRp110000000Widget5(),
              ),
              Positioned(
                left: 133.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 25.000001907348633,
                height: 25.0,
                child: GeneratedIconwishlistWidget4(),
              ),
              Positioned(
                left: 313.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 25.000001907348633,
                height: 25.0,
                child: GeneratedIconwishlistWidget5(),
              ),
              Positioned(
                left: 306.0,
                top: 792.0,
                right: null,
                bottom: null,
                width: 25.000001907348633,
                height: 25.0,
                child: GeneratedIconwishlistWidget6(),
              ),
              Positioned(
                left: 130.0,
                top: 792.0,
                right: null,
                bottom: null,
                width: 25.000001907348633,
                height: 25.0,
                child: GeneratedIconwishlistWidget7(),
              ),
              Positioned(
                left: 30.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 25.0,
                child: GeneratedKolomsearchWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 1.0,
                child: GeneratedLine28Widget3(),
              ),
              Positioned(
                left: 11.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 42.0,
                child: GeneratedIconhotsaleWidget1(),
              ),
              Positioned(
                left: 92.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 39.0,
                child: GeneratedIconmobilbaruWidget1(),
              ),
              Positioned(
                left: 184.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 43.0,
                child: GeneratedIconmobilbekasWidget1(),
              ),
              Positioned(
                left: 284.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 42.0,
                child: GeneratedIconpengaturanWidget1(),
              ),
              Positioned(
                left: 65.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedStar1Widget2(),
              ),
              Positioned(
                left: 245.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedStar2Widget2(),
              ),
              Positioned(
                left: 83.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 18.0,
                child: Generated485Widget1(),
              ),
              Positioned(
                left: 263.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 18.0,
                child: Generated475Widget1(),
              ),
              Positioned(
                left: 180.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 1.0,
                child: GeneratedLine29Widget2(),
              ),
              Positioned(
                left: 180.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 1.0,
                child: GeneratedLine30Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 1.0,
                child: GeneratedLine28Widget4(),
              ),
              Positioned(
                left: 11.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 21.0,
                child: GeneratedProductWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 617.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 140.0,
                child: GeneratedRectangle524Widget1(),
              ),
              Positioned(
                left: 200.0,
                top: 617.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 140.0,
                child: GeneratedRectangle525Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 140.0,
                child: GeneratedBanneratasWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedRectangle528Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget35(),
              ),
              Positioned(
                left: 265.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 26.0,
                child: GeneratedButtonloginWidget(),
              )
            ]),
      ),
    ));
  }
}
