import 'package:flutter/material.dart';

/* Text Guest
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGuestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Align(
      alignment: Alignment.center,
      child: Text(
        '''Guest''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 0.09,
          fontSize: 200.0,
          fontFamily: 'Arapey',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 255, 255, 255),

          /* letterSpacing: 0.0, */
        ),
      ),
    ));
  }
}
