import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedLine220Widget.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedFooterWidget21.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedProdukWidget45.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedHeaderWidget.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedLine222Widget.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedProdukWidget42.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedDaihatsuOfficial_StoreWidget.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedProdukWidget44.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedProdukWidget43.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedProdukTokoWidget.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedProdukWidget41.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedProdukWidget40.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedEllipse112Widget1.dart';
import 'package:flutterapp/mobilapp/generatedkunjungitokowidget/generated/GeneratedLine221Widget.dart';

/* Frame Kunjungi toko
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKunjungitokoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 990.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 990.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(10.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 130.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 100.0,
                              child: GeneratedEllipse112Widget1(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 103.0,
                              height: 25.0,
                              child: GeneratedProdukTokoWidget(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 200.0,
                              child: GeneratedProdukWidget40(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 470.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 200.0,
                              child: GeneratedProdukWidget41(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 690.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 200.0,
                              child: GeneratedProdukWidget42(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 200.0,
                              child: GeneratedProdukWidget43(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 470.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 200.0,
                              child: GeneratedProdukWidget44(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 690.0,
                              right: null,
                              bottom: null,
                              width: 140.0,
                              height: 200.0,
                              child: GeneratedProdukWidget45(),
                            ),
                            Positioned(
                              left: 98.0,
                              top: 173.0,
                              right: null,
                              bottom: null,
                              width: 169.0,
                              height: 25.0,
                              child: GeneratedDaihatsuOfficial_StoreWidget(),
                            ),
                            Positioned(
                              left: 180.0,
                              top: 250.0,
                              right: null,
                              bottom: null,
                              width: 645.0,
                              height: 1.0,
                              child: GeneratedLine220Widget(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 460.0,
                              right: null,
                              bottom: null,
                              width: 340.0,
                              height: 1.0,
                              child: GeneratedLine221Widget(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 680.0,
                              right: null,
                              bottom: null,
                              width: 340.0,
                              height: 1.0,
                              child: GeneratedLine222Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 50.0,
                              child: GeneratedHeaderWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 900.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 90.0,
                              child: GeneratedFooterWidget21(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
