import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaianwidget/generated/GeneratedBeriPenilaianWidget1.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaianwidget/generated/GeneratedAtasWidget15.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaianwidget/generated/GeneratedProdukWidget6.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaianwidget/generated/GeneratedRectangle161Widget1.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaianwidget/generated/GeneratedBeriPenilaianWidget2.dart';

/* Frame Beri Penilaian
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBeriPenilaianWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 200.0,
                              child: GeneratedAtasWidget15(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 225.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 68.0,
                              child: GeneratedBeriPenilaianWidget1(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 1360.0,
                              height: 362.0,
                              child: GeneratedProdukWidget6(),
                            ),
                            Positioned(
                              left: 1001.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 338.0,
                              height: 80.0,
                              child: GeneratedRectangle161Widget1(),
                            ),
                            Positioned(
                              left: 1047.0,
                              top: 654.0,
                              right: null,
                              bottom: null,
                              width: 247.0,
                              height: 55.0,
                              child: GeneratedBeriPenilaianWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
