import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget3/generated/GeneratedLine222Widget2.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget3/generated/GeneratedProdukWidget55.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget3/generated/GeneratedMobilBaruWidget40.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget3/generated/GeneratedLine220Widget2.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget3/generated/GeneratedProdukWidget53.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget3/generated/GeneratedProdukWidget52.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget3/generated/GeneratedFooterWidget24.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget3/generated/GeneratedProdukWidget57.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget3/generated/GeneratedProdukWidget56.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget3/generated/GeneratedHeaderWidget3.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget3/generated/GeneratedLine221Widget2.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget3/generated/GeneratedProdukWidget54.dart';

/* Frame mobil baru
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMobilbaruWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 850.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 109.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 20.0,
                child: GeneratedMobilBaruWidget40(),
              ),
              Positioned(
                left: 21.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget52(),
              ),
              Positioned(
                left: 21.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget53(),
              ),
              Positioned(
                left: 23.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget54(),
              ),
              Positioned(
                left: 210.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget55(),
              ),
              Positioned(
                left: 200.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget56(),
              ),
              Positioned(
                left: 202.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget57(),
              ),
              Positioned(
                left: 180.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 645.0,
                height: 1.0,
                child: GeneratedLine220Widget2(),
              ),
              Positioned(
                left: 10.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine221Widget2(),
              ),
              Positioned(
                left: 10.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine222Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedHeaderWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedFooterWidget24(),
              )
            ]),
      ),
    ));
  }
}
