import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget2/generated/GeneratedProdukWidget46.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget2/generated/GeneratedProdukWidget49.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget2/generated/GeneratedLine220Widget1.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget2/generated/GeneratedMobilBaruWidget38.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget2/generated/GeneratedLine222Widget1.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget2/generated/GeneratedProdukWidget48.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget2/generated/GeneratedProdukWidget50.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget2/generated/GeneratedLine221Widget1.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget2/generated/GeneratedProdukWidget47.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget2/generated/GeneratedProdukWidget51.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget2/generated/GeneratedFooterWidget23.dart';
import 'package:flutterapp/mobilapp/generatedmobilbaruwidget2/generated/GeneratedHeaderWidget2.dart';

/* Frame mobil baru
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMobilbaruWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 850.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 109.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 20.0,
                child: GeneratedMobilBaruWidget38(),
              ),
              Positioned(
                left: 21.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget46(),
              ),
              Positioned(
                left: 21.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget47(),
              ),
              Positioned(
                left: 23.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget48(),
              ),
              Positioned(
                left: 200.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget49(),
              ),
              Positioned(
                left: 200.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget50(),
              ),
              Positioned(
                left: 202.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 200.0,
                child: GeneratedProdukWidget51(),
              ),
              Positioned(
                left: 180.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 645.0,
                height: 1.0,
                child: GeneratedLine220Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine221Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 1.0,
                child: GeneratedLine222Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedHeaderWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedFooterWidget23(),
              )
            ]),
      ),
    ));
  }
}
