import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedRectangle752Widget.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedRectangle750Widget.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedReadyWarnaapaajakakWidget.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedRectangle753Widget.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedRectangle748Widget.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedAdablackmattedansilverkakWidget.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedEllipse113Widget4.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedBlackmattenyadoveyaWidget4.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedLine224Widget.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedRectangle747Widget.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedRectangle749Widget.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedRectangle751Widget.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedRianiWidget7.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedAtaslogoWidget35.dart';
import 'package:flutterapp/mobilapp/generatedchatdalemwidget/generated/GeneratedKirimPesanWidget.dart';

/* Frame chat dalem
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatdalemWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 400.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedRectangle747Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEllipse113Widget4(),
              ),
              Positioned(
                left: 70.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 27.0,
                child: GeneratedRianiWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedRectangle748Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 30.0,
                child: GeneratedRectangle749Widget(),
              ),
              Positioned(
                left: 318.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 22.0,
                child: GeneratedRectangle750Widget(),
              ),
              Positioned(
                left: 24.9990234375,
                top: 385.5,
                right: null,
                bottom: null,
                width: 270.0018615722656,
                height: 1.0,
                child: GeneratedLine224Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 365.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 18.0,
                child: GeneratedKirimPesanWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 20.0,
                child: GeneratedRectangle751Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 20.0,
                child: GeneratedRectangle753Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 20.0,
                child: GeneratedRectangle752Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 14.0,
                child: GeneratedReadyWarnaapaajakakWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 14.0,
                child: GeneratedBlackmattenyadoveyaWidget4(),
              ),
              Positioned(
                left: 204.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 14.0,
                child: GeneratedAdablackmattedansilverkakWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget35(),
              )
            ]),
      ),
    ));
  }
}
