import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedMOBILIKUWidget28.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedHondaWidget8.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedDaihatsuWidget8.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedWebsitepenjualanmobilterpecayaWidget8.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedMobilBekasWidget18.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedAkunWidget18.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedHyundaiWidget8.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedPengaturanWidget9.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedWishlistWidget15.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedToyotaWidget8.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedKatalogsayaWidget7.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedInstagram1Widget8.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedBMWWidget8.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedMobilBaruWidget18.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget8/generated/GeneratedRectangle172Widget8.dart';

/* Group footer
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFooterWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1440.0,
      height: 281.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 1440.0,
              height: 281.0,
              child: GeneratedRectangle172Widget8(),
            ),
            Positioned(
              left: 40.0,
              top: 46.0,
              right: null,
              bottom: null,
              width: 505.0,
              height: 91.0,
              child: GeneratedMOBILIKUWidget28(),
            ),
            Positioned(
              left: 1315.0,
              top: 200.0,
              right: null,
              bottom: null,
              width: 45.0,
              height: 45.0,
              child: GeneratedInstagram1Widget8(),
            ),
            Positioned(
              left: 720.0,
              top: 24.0,
              right: null,
              bottom: null,
              width: 105.0,
              height: 38.0,
              child: GeneratedMobilBaruWidget18(),
            ),
            Positioned(
              left: 720.0,
              top: 65.0,
              right: null,
              bottom: null,
              width: 86.0,
              height: 28.0,
              child: GeneratedDaihatsuWidget8(),
            ),
            Positioned(
              left: 1095.0,
              top: 65.0,
              right: null,
              bottom: null,
              width: 54.0,
              height: 28.0,
              child: GeneratedAkunWidget18(),
            ),
            Positioned(
              left: 1095.0,
              top: 93.0,
              right: null,
              bottom: null,
              width: 79.0,
              height: 28.0,
              child: GeneratedWishlistWidget15(),
            ),
            Positioned(
              left: 720.0,
              top: 93.0,
              right: null,
              bottom: null,
              width: 66.0,
              height: 28.0,
              child: GeneratedToyotaWidget8(),
            ),
            Positioned(
              left: 1095.0,
              top: 121.0,
              right: null,
              bottom: null,
              width: 115.0,
              height: 25.0,
              child: GeneratedKatalogsayaWidget7(),
            ),
            Positioned(
              left: 721.0,
              top: 121.0,
              right: null,
              bottom: null,
              width: 54.0,
              height: 28.0,
              child: GeneratedBMWWidget8(),
            ),
            Positioned(
              left: 720.0,
              top: 149.0,
              right: null,
              bottom: null,
              width: 64.0,
              height: 28.0,
              child: GeneratedHondaWidget8(),
            ),
            Positioned(
              left: 720.0,
              top: 177.0,
              right: null,
              bottom: null,
              width: 83.0,
              height: 28.0,
              child: GeneratedHyundaiWidget8(),
            ),
            Positioned(
              left: 900.0,
              top: 24.0,
              right: null,
              bottom: null,
              width: 120.0,
              height: 38.0,
              child: GeneratedMobilBekasWidget18(),
            ),
            Positioned(
              left: 1095.0,
              top: 20.0,
              right: null,
              bottom: null,
              width: 115.0,
              height: 41.0,
              child: GeneratedPengaturanWidget9(),
            ),
            Positioned(
              left: 119.0,
              top: 149.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 28.0,
              child: GeneratedWebsitepenjualanmobilterpecayaWidget8(),
            )
          ]),
    ));
  }
}
