import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedProdukjualanWidget8.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedPilihanwarnaWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedEditbarangWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedLine50Widget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedkeranjangWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedJudulWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedAtasWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedKeranjangWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedProdukjualanWidget9.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedGambarbawahutamaWidget4.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedHargaWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedGambarbawahutamaWidget6.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedGambarbawahutamaWidget5.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedGambarbawahutamaWidget7.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedProdukjualanWidget5.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedProdukjualanWidget6.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedIconchatWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedJumlahbarangyangterjualWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedKomentarWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedLogoWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedRattingprodukWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedGambarutamaWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedWishlistWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukuseradminwidget/generated/GeneratedProdukjualanWidget7.dart';

/* Frame klik produk user / admin
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKlikprodukuseradminWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2000.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 2000.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1.0,
                              right: null,
                              bottom: null,
                              width: 1440.036376953125,
                              height: 160.0,
                              child: GeneratedAtasWidget1(),
                            ),
                            Positioned(
                              left: 540.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 360.0000305175781,
                              height: 120.0,
                              child: GeneratedLogoWidget1(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 201.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 400.0,
                              child: GeneratedGambarutamaWidget1(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedGambarbawahutamaWidget4(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedGambarbawahutamaWidget5(),
                            ),
                            Positioned(
                              left: 260.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedGambarbawahutamaWidget6(),
                            ),
                            Positioned(
                              left: 360.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedGambarbawahutamaWidget7(),
                            ),
                            Positioned(
                              left: 500.0,
                              top: 221.0,
                              right: null,
                              bottom: null,
                              width: 540.0,
                              height: 80.0,
                              child: GeneratedHargaWidget1(),
                            ),
                            Positioned(
                              left: 500.0,
                              top: 321.0,
                              right: null,
                              bottom: null,
                              width: 200.0,
                              height: 40.0,
                              child: GeneratedJudulWidget1(),
                            ),
                            Positioned(
                              left: 500.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 41.0,
                              child: GeneratedPilihanwarnaWidget1(),
                            ),
                            Positioned(
                              left: 1280.0,
                              top: 41.0,
                              right: null,
                              bottom: null,
                              width: 80.0,
                              height: 80.0,
                              child: GeneratedKeranjangWidget1(),
                            ),
                            Positioned(
                              left: 1160.0,
                              top: 41.0,
                              right: null,
                              bottom: null,
                              width: 80.0,
                              height: 80.0,
                              child: GeneratedIconchatWidget1(),
                            ),
                            Positioned(
                              left: 860.0,
                              top: 341.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 61.0,
                              child: GeneratedWishlistWidget1(),
                            ),
                            Positioned(
                              left: 780.0,
                              top: 341.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 61.0,
                              child: GeneratedEditbarangWidget(),
                            ),
                            Positioned(
                              left: 940.0,
                              top: 341.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedkeranjangWidget1(),
                            ),
                            Positioned(
                              left: 1080.0,
                              top: 160.0,
                              right: null,
                              bottom: null,
                              width: 1840.0,
                              height: 1.0,
                              child: GeneratedLine50Widget1(),
                            ),
                            Positioned(
                              left: 1120.0,
                              top: 202.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 300.0,
                              child: GeneratedProdukjualanWidget5(),
                            ),
                            Positioned(
                              left: 1120.0,
                              top: 922.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 300.0,
                              child: GeneratedProdukjualanWidget6(),
                            ),
                            Positioned(
                              left: 1120.0,
                              top: 562.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 300.0,
                              child: GeneratedProdukjualanWidget7(),
                            ),
                            Positioned(
                              left: 1120.0,
                              top: 1282.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 300.0,
                              child: GeneratedProdukjualanWidget8(),
                            ),
                            Positioned(
                              left: 1120.0,
                              top: 1642.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 300.0,
                              child: GeneratedProdukjualanWidget9(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 781.0,
                              right: null,
                              bottom: null,
                              width: 440.0,
                              height: 80.0,
                              child: GeneratedRattingprodukWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 741.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 20.0,
                              child: GeneratedJumlahbarangyangterjualWidget1(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 1080.0,
                              right: null,
                              bottom: null,
                              width: 961.0,
                              height: 560.0,
                              child: GeneratedKomentarWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
