import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedchatawalwidget/generated/GeneratedChatWidget6.dart';
import 'package:flutterapp/mobilapp/generatedchatawalwidget/generated/GeneratedChatWidget7.dart';
import 'package:flutterapp/mobilapp/generatedchatawalwidget/generated/GeneratedChatWidget5.dart';
import 'package:flutterapp/mobilapp/generatedchatawalwidget/generated/GeneratedIconchatWidget27.dart';
import 'package:flutterapp/mobilapp/generatedchatawalwidget/generated/GeneratedAtaslogoWidget34.dart';
import 'package:flutterapp/mobilapp/generatedchatawalwidget/generated/GeneratedMOBILIKUWidget69.dart';
import 'package:flutterapp/mobilapp/generatedchatawalwidget/generated/GeneratedChatWidget8.dart';

/* Frame chat awal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatawalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 10.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 70.0,
                child: GeneratedChatWidget5(),
              ),
              Positioned(
                left: 10.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 70.0,
                child: GeneratedChatWidget6(),
              ),
              Positioned(
                left: 10.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 70.0,
                child: GeneratedChatWidget7(),
              ),
              Positioned(
                left: 10.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 70.0,
                child: GeneratedChatWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget34(),
              ),
              Positioned(
                left: 312.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconchatWidget27(),
              ),
              Positioned(
                left: 121.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget69(),
              )
            ]),
      ),
    ));
  }
}
