import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget/generated/GeneratedButtondeleteWidget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget/generated/GeneratedAtasWidget6.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget/generated/GeneratedFotoproductWidget1.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget/generated/GeneratedButtonuploadWidget3.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget/generated/GeneratedUploadWidget1.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget/generated/GeneratedDescprodukWidget3.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget/generated/GeneratedLogoWidget5.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget/generated/GeneratedLine109Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget/generated/GeneratedDetailWidget1.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget/generated/GeneratedDeleteWidget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget/generated/GeneratedLine110Widget.dart';
import 'package:flutterapp/mobilapp/generatedcrudbarangwidget/generated/GeneratedDeskripsiprodukWidget.dart';

/* Frame CRUD barang
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCRUDbarangWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2000.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 2000.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 400.0,
                              child: GeneratedFotoproductWidget1(),
                            ),
                            Positioned(
                              left: 520.0,
                              top: 221.0,
                              right: null,
                              bottom: null,
                              width: 780.0,
                              height: 559.0,
                              child: GeneratedDetailWidget1(),
                            ),
                            Positioned(
                              left: 520.0,
                              top: 820.0,
                              right: null,
                              bottom: null,
                              width: 780.0,
                              height: 220.0,
                              child: GeneratedDescprodukWidget3(),
                            ),
                            Positioned(
                              left: 540.0,
                              top: 839.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 31.0,
                              child: GeneratedDeskripsiprodukWidget(),
                            ),
                            Positioned(
                              left: 460.0,
                              top: 1120.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 80.0,
                              child: GeneratedButtondeleteWidget(),
                            ),
                            Positioned(
                              left: 800.0,
                              top: 1120.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 80.0,
                              child: GeneratedButtonuploadWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.036376953125,
                              height: 160.0,
                              child: GeneratedAtasWidget6(),
                            ),
                            Positioned(
                              left: 540.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 360.0000305175781,
                              height: 120.0,
                              child: GeneratedLogoWidget5(),
                            ),
                            Positioned(
                              left: 513.0,
                              top: 1145.0,
                              right: null,
                              bottom: null,
                              width: 79.0,
                              height: 34.0,
                              child: GeneratedDeleteWidget(),
                            ),
                            Positioned(
                              left: 850.0,
                              top: 1145.0,
                              right: null,
                              bottom: null,
                              width: 86.0,
                              height: 34.0,
                              child: GeneratedUploadWidget1(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 221.0,
                              right: null,
                              bottom: null,
                              width: 564.978759765625,
                              height: 1.0,
                              child: GeneratedLine109Widget(),
                            ),
                            Positioned(
                              left: 59.0,
                              top: 619.0,
                              right: null,
                              bottom: null,
                              width: 564.9822998046875,
                              height: 1.0,
                              child: GeneratedLine110Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
