import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedGroup45Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedAtaslogoWidget17.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedGroup44Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedGroup46Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedIconchatWidget13.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedEllipse112Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedFooterWidget15.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedMOBILIKUWidget52.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedIconhomeWidget11.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedGroup42Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedRectangle616Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedGroup47Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedGroup48Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedRectangle736Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedGroup43Widget.dart';
import 'package:flutterapp/mobilapp/generatedakunwidget24/generated/GeneratedIndahWidget.dart';

/* Frame akun
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAkunWidget24 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 100.0,
                child: GeneratedRectangle736Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedEllipse112Widget(),
              ),
              Positioned(
                left: 121.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 38.0,
                child: GeneratedIndahWidget(),
              ),
              Positioned(
                left: 300.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedRectangle616Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedGroup42Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedGroup43Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedGroup44Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedGroup45Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedGroup46Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 520.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedGroup47Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedGroup48Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget17(),
              ),
              Positioned(
                left: 23.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconhomeWidget11(),
              ),
              Positioned(
                left: 312.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconchatWidget13(),
              ),
              Positioned(
                left: 121.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget52(),
              ),
              Positioned(
                left: 0.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedFooterWidget15(),
              )
            ]),
      ),
    ));
  }
}
