import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedProduk2Widget3.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine195Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle194Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedEllipse8Widget1.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine192Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle195Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine194Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle191Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine193Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine34Widget6.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle185Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine190Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedDaihatsuOfficialStoreWidget1.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine183Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine182Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle186Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle213Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedHomepageatasWidget7.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle188Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine191Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle192Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle189Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine187Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine33Widget4.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedFooterWidget1.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle160Widget1.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedProduk1Widget3.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle190Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle212Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle210Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine186Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine189Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle187Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle193Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedRectangle211Widget.dart';
import 'package:flutterapp/mobilapp/generatedkatalogsayawidget1/generated/GeneratedLine188Widget.dart';

/* Frame Katalog Saya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKatalogSayaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1585.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1585.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 240.0,
                              child: GeneratedHomepageatasWidget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 320.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 220.0,
                              child: GeneratedRectangle160Widget1(),
                            ),
                            Positioned(
                              left: 409.0,
                              top: 340.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 180.0,
                              child: GeneratedEllipse8Widget1(),
                            ),
                            Positioned(
                              left: 627.0,
                              top: 404.0,
                              right: null,
                              bottom: null,
                              width: 405.0,
                              height: 55.0,
                              child: GeneratedDaihatsuOfficialStoreWidget1(),
                            ),
                            Positioned(
                              left: 111.0,
                              top: 590.0,
                              right: null,
                              bottom: null,
                              width: 1201.0,
                              height: 300.0,
                              child: GeneratedProduk1Widget3(),
                            ),
                            Positioned(
                              left: 486.625,
                              top: 639.96728515625,
                              right: null,
                              bottom: null,
                              width: 660.0,
                              height: 1.0,
                              child: GeneratedLine33Widget4(),
                            ),
                            Positioned(
                              left: 940.533203125,
                              top: 639.9404296875,
                              right: null,
                              bottom: null,
                              width: 660.0,
                              height: 1.0,
                              child: GeneratedLine34Widget6(),
                            ),
                            Positioned(
                              left: 114.0,
                              top: 920.0,
                              right: null,
                              bottom: null,
                              width: 1201.0,
                              height: 300.0,
                              child: GeneratedProduk2Widget3(),
                            ),
                            Positioned(
                              left: 489.625,
                              top: 969.96728515625,
                              right: null,
                              bottom: null,
                              width: 660.0,
                              height: 1.0,
                              child: GeneratedLine194Widget(),
                            ),
                            Positioned(
                              left: 943.533203125,
                              top: 969.9404296875,
                              right: null,
                              bottom: null,
                              width: 660.0,
                              height: 1.0,
                              child: GeneratedLine195Widget(),
                            ),
                            Positioned(
                              left: 472.0,
                              top: 60.0,
                              right: null,
                              bottom: null,
                              width: 488.0,
                              height: 80.0,
                              child: GeneratedRectangle210Widget(),
                            ),
                            Positioned(
                              left: 470.0,
                              top: 140.0,
                              right: null,
                              bottom: null,
                              width: 496.4876708984375,
                              height: 1.0,
                              child: GeneratedLine186Widget(),
                            ),
                            Positioned(
                              left: 470.0,
                              top: 60.0,
                              right: null,
                              bottom: null,
                              width: 496.4876708984375,
                              height: 1.0,
                              child: GeneratedLine187Widget(),
                            ),
                            Positioned(
                              left: 1180.0,
                              top: 72.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 68.0,
                              child: GeneratedRectangle211Widget(),
                            ),
                            Positioned(
                              left: 1240.0,
                              top: 72.0,
                              right: null,
                              bottom: null,
                              width: 90.68627166748047,
                              height: 1.0,
                              child: GeneratedLine188Widget(),
                            ),
                            Positioned(
                              left: 1180.0,
                              top: 72.0,
                              right: null,
                              bottom: null,
                              width: 90.68627166748047,
                              height: 1.0,
                              child: GeneratedLine189Widget(),
                            ),
                            Positioned(
                              left: 1300.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 70.0,
                              child: GeneratedRectangle212Widget(),
                            ),
                            Positioned(
                              left: 1360.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 92.19544219970703,
                              height: 1.0,
                              child: GeneratedLine190Widget(),
                            ),
                            Positioned(
                              left: 1300.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 92.19544219970703,
                              height: 1.0,
                              child: GeneratedLine191Widget(),
                            ),
                            Positioned(
                              left: 400.0,
                              top: 340.0,
                              right: null,
                              bottom: null,
                              width: 198.0,
                              height: 180.0,
                              child: GeneratedEllipse10Widget(),
                            ),
                            Positioned(
                              left: 570.0,
                              top: 366.0,
                              right: null,
                              bottom: null,
                              width: 186.81005859375,
                              height: 1.0,
                              child: GeneratedLine192Widget(),
                            ),
                            Positioned(
                              left: 429.0,
                              top: 367.0,
                              right: null,
                              bottom: null,
                              width: 189.09521484375,
                              height: 1.0,
                              child: GeneratedLine193Widget(),
                            ),
                            Positioned(
                              left: 620.0,
                              top: 409.0,
                              right: null,
                              bottom: null,
                              width: 420.0,
                              height: 38.0,
                              child: GeneratedRectangle213Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1304.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 281.0,
                              child: GeneratedFooterWidget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 1364.0,
                              right: null,
                              bottom: null,
                              width: 487.0,
                              height: 80.0,
                              child: GeneratedRectangle185Widget(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 1454.0,
                              right: null,
                              bottom: null,
                              width: 340.0,
                              height: 25.0,
                              child: GeneratedRectangle186Widget(),
                            ),
                            Positioned(
                              left: 720.0,
                              top: 1373.0,
                              right: null,
                              bottom: null,
                              width: 81.0,
                              height: 14.0,
                              child: GeneratedRectangle187Widget(),
                            ),
                            Positioned(
                              left: 720.0,
                              top: 1402.0,
                              right: null,
                              bottom: null,
                              width: 81.0,
                              height: 18.0,
                              child: GeneratedRectangle188Widget(),
                            ),
                            Positioned(
                              left: 721.0,
                              top: 1430.0,
                              right: null,
                              bottom: null,
                              width: 81.0,
                              height: 18.0,
                              child: GeneratedRectangle189Widget(),
                            ),
                            Positioned(
                              left: 721.0,
                              top: 1454.0,
                              right: null,
                              bottom: null,
                              width: 81.0,
                              height: 18.0,
                              child: GeneratedRectangle190Widget(),
                            ),
                            Positioned(
                              left: 721.0,
                              top: 1485.0,
                              right: null,
                              bottom: null,
                              width: 81.0,
                              height: 18.0,
                              child: GeneratedRectangle191Widget(),
                            ),
                            Positioned(
                              left: 1094.0,
                              top: 1373.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 14.0,
                              child: GeneratedRectangle192Widget(),
                            ),
                            Positioned(
                              left: 1095.0,
                              top: 1401.0,
                              right: null,
                              bottom: null,
                              width: 73.0,
                              height: 14.0,
                              child: GeneratedRectangle193Widget(),
                            ),
                            Positioned(
                              left: 1094.0,
                              top: 1429.0,
                              right: null,
                              bottom: null,
                              width: 114.0,
                              height: 21.0,
                              child: GeneratedRectangle194Widget(),
                            ),
                            Positioned(
                              left: 1313.0,
                              top: 1504.0,
                              right: null,
                              bottom: null,
                              width: 47.0,
                              height: 47.0,
                              child: GeneratedRectangle195Widget(),
                            ),
                            Positioned(
                              left: 528.0,
                              top: 1364.0,
                              right: null,
                              bottom: null,
                              width: 494.513916015625,
                              height: 1.0,
                              child: GeneratedLine182Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 1364.0,
                              right: null,
                              bottom: null,
                              width: 493.527099609375,
                              height: 1.0,
                              child: GeneratedLine183Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
