import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedRectangle532Widget.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedLogInWidget7.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedSegitigaWidget6.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedRectangle534Widget.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedRectangle533Widget.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedForgotPasswordWidget.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedPasswordWidget4.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedAtaslogoWidget3.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedUsernameEmailWidget.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedRectangle535Widget.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedLogInWidget8.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedRectangle531Widget.dart';
import 'package:flutterapp/mobilapp/generatedloginwidget6/generated/GeneratedDonthaveanaccountSignUpWidget.dart';

/* Frame Log In
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogInWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 800.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -143.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 483.1653747558594,
                height: 451.30841064453125,
                child: GeneratedSegitigaWidget6(),
              ),
              Positioned(
                left: 30.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 122.0,
                child: GeneratedRectangle531Widget(),
              ),
              Positioned(
                left: 153.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 29.0,
                child: GeneratedLogInWidget7(),
              ),
              Positioned(
                left: 50.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 30.0,
                child: GeneratedRectangle532Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 30.0,
                child: GeneratedRectangle533Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 19.0,
                child: GeneratedUsernameEmailWidget(),
              ),
              Positioned(
                left: 60.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 22.0,
                child: GeneratedPasswordWidget4(),
              ),
              Positioned(
                left: 110.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 23.0,
                child: GeneratedRectangle534Widget(),
              ),
              Positioned(
                left: 110.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 23.0,
                child: GeneratedRectangle535Widget(),
              ),
              Positioned(
                left: 163.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 17.0,
                child: GeneratedLogInWidget8(),
              ),
              Positioned(
                left: 133.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 17.0,
                child: GeneratedForgotPasswordWidget(),
              ),
              Positioned(
                left: 82.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 29.0,
                child: GeneratedDonthaveanaccountSignUpWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget3(),
              )
            ]),
      ),
    ));
  }
}
