import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedIconhomeWidget7.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedKunjungiTokoWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedRectangle727Widget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedLine32Widget4.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedIconchatWidget10.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedDeskripsiProdukDesainDasborPenuhBaruyangMencolokTipe15G1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedProdukWidget30.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedGroup41Widget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedProdkWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedToyotaAvanzaAllNewGTypeWidget2.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedFotoprodukWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedMOBILIKUWidget48.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedRattingWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedRp255100000Widget3.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedKomenWidget3.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedLine80Widget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedWarnaWidget2.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedRectangle677Widget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedAtaslogoWidget13.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedDesprodukWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedToyotaOfficialWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget3/generated/GeneratedBawahWidget2.dart';

/* Frame klik produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKlikprodukWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1182.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1181.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(10.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 300.0,
                              child: GeneratedFotoprodukWidget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 480.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 150.0,
                              child: GeneratedDesprodukWidget1(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 485.0,
                              right: null,
                              bottom: null,
                              width: 311.0,
                              height: 135.0,
                              child:
                                  GeneratedDeskripsiProdukDesainDasborPenuhBaruyangMencolokTipe15G1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 395.0,
                              right: null,
                              bottom: null,
                              width: 214.0,
                              height: 22.0,
                              child: GeneratedToyotaAvanzaAllNewGTypeWidget2(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 439.0,
                              right: null,
                              bottom: null,
                              width: 107.0,
                              height: 22.0,
                              child: GeneratedRp255100000Widget3(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 130.0,
                              child: GeneratedKomenWidget3(),
                            ),
                            Positioned(
                              left: 250.0,
                              top: 393.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 25.0,
                              child: GeneratedWarnaWidget2(),
                            ),
                            Positioned(
                              left: 290.0,
                              top: 434.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 30.0,
                              child: GeneratedRattingWidget1(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 701.0,
                              right: null,
                              bottom: null,
                              width: 300.0,
                              height: 1.0,
                              child: GeneratedLine80Widget1(),
                            ),
                            Positioned(
                              left: 251.0,
                              top: 437.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedRectangle677Widget1(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 790.0,
                              right: null,
                              bottom: null,
                              width: 80.0,
                              height: 80.0,
                              child: GeneratedGroup41Widget1(),
                            ),
                            Positioned(
                              left: 240.0,
                              top: 820.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 20.0,
                              child: GeneratedRectangle727Widget1(),
                            ),
                            Positioned(
                              left: 252.0,
                              top: 821.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 20.0,
                              child: GeneratedKunjungiTokoWidget1(),
                            ),
                            Positioned(
                              left: 114.0,
                              top: 821.0,
                              right: null,
                              bottom: null,
                              width: 107.0,
                              height: 23.0,
                              child: GeneratedToyotaOfficialWidget1(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 881.0,
                              right: null,
                              bottom: null,
                              width: 141.0,
                              height: 200.0,
                              child: GeneratedProdukWidget30(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 70.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 1011.0,
                              child: GeneratedProdkWidget1(),
                            ),
                            Positioned(
                              left: 180.0,
                              top: 877.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 1.0,
                              child: GeneratedLine32Widget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1112.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 70.0,
                              child: GeneratedBawahWidget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 50.0,
                              child: GeneratedAtaslogoWidget13(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 25.0,
                              child: GeneratedIconhomeWidget7(),
                            ),
                            Positioned(
                              left: 312.0,
                              top: 13.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 25.0,
                              child: GeneratedIconchatWidget10(),
                            ),
                            Positioned(
                              left: 121.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 123.0,
                              height: 28.0,
                              child: GeneratedMOBILIKUWidget48(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
