import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedgambarbawahutamawidget10/generated/GeneratedRectangle55Widget10.dart';

/* Group Gambar bawah utama
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGambarbawahutamaWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 60.0,
      height: 60.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(5.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 60.0,
              height: 60.0,
              child: GeneratedRectangle55Widget10(),
            )
          ]),
    ));
  }
}
