import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedProdukWidget17.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedLine35Widget9.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedTitleWidget.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedProdukWidget18.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedProdukWidget16.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedFooterWidget13.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedProdukWidget13.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedLine34Widget7.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedLine36Widget11.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedProdukWidget12.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedSegitigaWidget10.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedAtaslogoWidget7.dart';
import 'package:flutterapp/mobilapp/generatedhotsalewidget14/generated/GeneratedProdukWidget14.dart';

/* Frame Hot Sale
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHotSaleWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 910.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 910.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(10.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -157.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 483.1653747558594,
                              height: 451.30841064453125,
                              child: GeneratedSegitigaWidget10(),
                            ),
                            Positioned(
                              left: 126.0,
                              top: 60.0,
                              right: null,
                              bottom: null,
                              width: 113.0,
                              height: 60.0,
                              child: GeneratedTitleWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 150.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 199.0,
                              child: GeneratedProdukWidget12(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 200.0,
                              child: GeneratedProdukWidget13(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 610.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 199.0,
                              child: GeneratedProdukWidget14(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 610.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 199.0,
                              child: GeneratedProdukWidget16(),
                            ),
                            Positioned(
                              left: 200.0,
                              top: 380.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 200.0,
                              child: GeneratedProdukWidget17(),
                            ),
                            Positioned(
                              left: 190.0,
                              top: 150.0,
                              right: null,
                              bottom: null,
                              width: 155.0,
                              height: 199.0,
                              child: GeneratedProdukWidget18(),
                            ),
                            Positioned(
                              left: 180.507568359375,
                              top: 149.99961853027344,
                              right: null,
                              bottom: null,
                              width: 670.000732421875,
                              height: 1.0,
                              child: GeneratedLine34Widget7(),
                            ),
                            Positioned(
                              left: 9.99926471710205,
                              top: 361.5,
                              right: null,
                              bottom: null,
                              width: 340.00146484375,
                              height: 1.0,
                              child: GeneratedLine35Widget9(),
                            ),
                            Positioned(
                              left: 10.99926471710205,
                              top: 590.5,
                              right: null,
                              bottom: null,
                              width: 340.00146484375,
                              height: 1.0,
                              child: GeneratedLine36Widget11(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 50.0,
                              child: GeneratedAtaslogoWidget7(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 820.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 90.0,
                              child: GeneratedFooterWidget13(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
