import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedJudulWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedGambarbawahutamaWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedProdukjualanWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedIconchatWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedLine50Widget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedDescprodukWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedAtasWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedRattingprodukWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedKeranjangWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedWishlistWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedProdukjualanWidget3.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedGambarutamaWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedJumlahbarangyangterjualWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedProdukjualanWidget2.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedGambarbawahutamaWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedkeranjangWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedHargaWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedProdukjualanWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedGambarbawahutamaWidget3.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedProdukjualanWidget4.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedLogoWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedKomentarWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedPilihanwarnaWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukwidget/generated/GeneratedGambarbawahutamaWidget2.dart';

/* Frame klik produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKlikprodukWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2000.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 2000.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1.0,
                              right: null,
                              bottom: null,
                              width: 1440.036376953125,
                              height: 160.0,
                              child: GeneratedAtasWidget(),
                            ),
                            Positioned(
                              left: 540.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 360.0000305175781,
                              height: 120.0,
                              child: GeneratedLogoWidget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 201.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 400.0,
                              child: GeneratedGambarutamaWidget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedGambarbawahutamaWidget(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedGambarbawahutamaWidget1(),
                            ),
                            Positioned(
                              left: 260.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedGambarbawahutamaWidget2(),
                            ),
                            Positioned(
                              left: 360.0,
                              top: 640.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedGambarbawahutamaWidget3(),
                            ),
                            Positioned(
                              left: 500.0,
                              top: 221.0,
                              right: null,
                              bottom: null,
                              width: 540.0,
                              height: 80.0,
                              child: GeneratedHargaWidget(),
                            ),
                            Positioned(
                              left: 500.0,
                              top: 321.0,
                              right: null,
                              bottom: null,
                              width: 200.0,
                              height: 40.0,
                              child: GeneratedJudulWidget(),
                            ),
                            Positioned(
                              left: 500.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 41.0,
                              child: GeneratedPilihanwarnaWidget(),
                            ),
                            Positioned(
                              left: 1280.0,
                              top: 41.0,
                              right: null,
                              bottom: null,
                              width: 80.0,
                              height: 80.0,
                              child: GeneratedKeranjangWidget(),
                            ),
                            Positioned(
                              left: 1160.0,
                              top: 41.0,
                              right: null,
                              bottom: null,
                              width: 80.0,
                              height: 80.0,
                              child: GeneratedIconchatWidget(),
                            ),
                            Positioned(
                              left: 860.0,
                              top: 341.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 61.0,
                              child: GeneratedWishlistWidget(),
                            ),
                            Positioned(
                              left: 940.0,
                              top: 341.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedkeranjangWidget(),
                            ),
                            Positioned(
                              left: 1080.0,
                              top: 160.0,
                              right: null,
                              bottom: null,
                              width: 1840.0,
                              height: 1.0,
                              child: GeneratedLine50Widget(),
                            ),
                            Positioned(
                              left: 1120.0,
                              top: 202.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 300.0,
                              child: GeneratedProdukjualanWidget(),
                            ),
                            Positioned(
                              left: 1120.0,
                              top: 922.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 300.0,
                              child: GeneratedProdukjualanWidget1(),
                            ),
                            Positioned(
                              left: 1120.0,
                              top: 562.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 300.0,
                              child: GeneratedProdukjualanWidget2(),
                            ),
                            Positioned(
                              left: 1120.0,
                              top: 1282.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 300.0,
                              child: GeneratedProdukjualanWidget3(),
                            ),
                            Positioned(
                              left: 1120.0,
                              top: 1642.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 300.0,
                              child: GeneratedProdukjualanWidget4(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 781.0,
                              right: null,
                              bottom: null,
                              width: 440.0,
                              height: 80.0,
                              child: GeneratedRattingprodukWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 741.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 20.0,
                              child: GeneratedJumlahbarangyangterjualWidget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 1080.0,
                              right: null,
                              bottom: null,
                              width: 961.0,
                              height: 560.0,
                              child: GeneratedKomentarWidget(),
                            ),
                            Positioned(
                              left: 501.0,
                              top: 460.0,
                              right: null,
                              bottom: null,
                              width: 520.0,
                              height: 600.0,
                              child: GeneratedDescprodukWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
