import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generateddikirimwidget/generated/GeneratedAtasWidget12.dart';
import 'package:flutterapp/mobilapp/generateddikirimwidget/generated/GeneratedDikirimWidget.dart';
import 'package:flutterapp/mobilapp/generateddikirimwidget/generated/GeneratedProdukWidget2.dart';

/* Frame DIkirim
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDIkirimWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 1440.0,
        height: 867.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 1440.0,
                height: 200.0,
                child: GeneratedAtasWidget12(),
              ),
              Positioned(
                left: 60.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 71.0,
                child: GeneratedDikirimWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 1360.0,
                height: 362.0,
                child: GeneratedProdukWidget2(),
              )
            ]),
      ),
    ));
  }
}
