import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedMOBILIKUWidget25.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedWebsitepenjualanmobilterpecayaWidget5.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedKatalogsayaWidget4.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedRectangle172Widget5.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedHondaWidget5.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedBMWWidget5.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedAkunWidget15.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedMobilBaruWidget15.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedToyotaWidget5.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedPengaturanWidget6.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedWishlistWidget12.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedMobilBekasWidget15.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedHyundaiWidget5.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedDaihatsuWidget5.dart';
import 'package:flutterapp/mobilapp/generatedfooterwidget5/generated/GeneratedInstagram1Widget5.dart';

/* Group footer
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFooterWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 1440.0,
      height: 281.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 1440.0,
              height: 281.0,
              child: GeneratedRectangle172Widget5(),
            ),
            Positioned(
              left: 40.0,
              top: 46.0,
              right: null,
              bottom: null,
              width: 505.0,
              height: 91.0,
              child: GeneratedMOBILIKUWidget25(),
            ),
            Positioned(
              left: 1315.0,
              top: 200.0,
              right: null,
              bottom: null,
              width: 45.0,
              height: 45.0,
              child: GeneratedInstagram1Widget5(),
            ),
            Positioned(
              left: 720.0,
              top: 24.0,
              right: null,
              bottom: null,
              width: 105.0,
              height: 38.0,
              child: GeneratedMobilBaruWidget15(),
            ),
            Positioned(
              left: 720.0,
              top: 65.0,
              right: null,
              bottom: null,
              width: 86.0,
              height: 28.0,
              child: GeneratedDaihatsuWidget5(),
            ),
            Positioned(
              left: 1095.0,
              top: 65.0,
              right: null,
              bottom: null,
              width: 54.0,
              height: 28.0,
              child: GeneratedAkunWidget15(),
            ),
            Positioned(
              left: 720.0,
              top: 93.0,
              right: null,
              bottom: null,
              width: 66.0,
              height: 28.0,
              child: GeneratedToyotaWidget5(),
            ),
            Positioned(
              left: 1095.0,
              top: 121.0,
              right: null,
              bottom: null,
              width: 115.0,
              height: 25.0,
              child: GeneratedKatalogsayaWidget4(),
            ),
            Positioned(
              left: 1095.0,
              top: 93.0,
              right: null,
              bottom: null,
              width: 79.0,
              height: 28.0,
              child: GeneratedWishlistWidget12(),
            ),
            Positioned(
              left: 721.0,
              top: 121.0,
              right: null,
              bottom: null,
              width: 54.0,
              height: 28.0,
              child: GeneratedBMWWidget5(),
            ),
            Positioned(
              left: 720.0,
              top: 149.0,
              right: null,
              bottom: null,
              width: 64.0,
              height: 28.0,
              child: GeneratedHondaWidget5(),
            ),
            Positioned(
              left: 720.0,
              top: 177.0,
              right: null,
              bottom: null,
              width: 83.0,
              height: 28.0,
              child: GeneratedHyundaiWidget5(),
            ),
            Positioned(
              left: 900.0,
              top: 24.0,
              right: null,
              bottom: null,
              width: 120.0,
              height: 38.0,
              child: GeneratedMobilBekasWidget15(),
            ),
            Positioned(
              left: 1095.0,
              top: 20.0,
              right: null,
              bottom: null,
              width: 115.0,
              height: 41.0,
              child: GeneratedPengaturanWidget6(),
            ),
            Positioned(
              left: 119.0,
              top: 149.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 28.0,
              child: GeneratedWebsitepenjualanmobilterpecayaWidget5(),
            )
          ]),
    ));
  }
}
