import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedRectangle606Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedRectangle608Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedRectangle609Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedAtaslogoWidget16.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedLine101Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedDeskripsiWidget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedTambahgambarWidget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedMobilbarubekasWidget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedMerkWidget3.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedRectangle605Widget1.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedLine100Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedRectangle610Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedAddproductWidget1.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedIconhomeWidget10.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedUploadWidget2.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedRectangle607Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedRectangle612Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedCancelWidget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedLine99Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedLine103Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedRectangle735Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedTahunWidget1.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedWarnaWidget4.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedRectangle733Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedLine104Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedLine102Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedNamaProdukWidget1.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedMOBILIKUWidget51.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedRectangle613Widget.dart';
import 'package:flutterapp/mobilapp/generatedaddprodukwidget/generated/GeneratedRectangle611Widget.dart';

/* Frame add produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddprodukWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 821.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 21.0,
                top: 59.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 21.0,
                child: GeneratedAddproductWidget1(),
              ),
              Positioned(
                left: 10.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 340.0,
                child: GeneratedRectangle735Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 300.0,
                child: GeneratedRectangle605Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 30.0,
                child: GeneratedRectangle606Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 30.0,
                child: GeneratedRectangle607Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 30.0,
                child: GeneratedRectangle608Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 30.0,
                child: GeneratedRectangle609Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 30.0,
                child: GeneratedRectangle610Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 20.0,
                child: GeneratedNamaProdukWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 20.0,
                child: GeneratedMobilbarubekasWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 23.0,
                child: GeneratedMerkWidget3(),
              ),
              Positioned(
                left: 32.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 23.0,
                child: GeneratedWarnaWidget4(),
              ),
              Positioned(
                left: 32.0,
                top: 646.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 23.0,
                child: GeneratedTahunWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 70.0,
                child: GeneratedRectangle611Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 700.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 23.0,
                child: GeneratedDeskripsiWidget(),
              ),
              Positioned(
                left: 200.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 30.0,
                child: GeneratedRectangle612Widget(),
              ),
              Positioned(
                left: 238.0,
                top: 786.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 23.0,
                child: GeneratedUploadWidget2(),
              ),
              Positioned(
                left: 40.0,
                top: 780.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 30.0,
                child: GeneratedRectangle613Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 786.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 23.0,
                child: GeneratedCancelWidget(),
              ),
              Positioned(
                left: 120.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 30.0,
                child: GeneratedRectangle733Widget(),
              ),
              Positioned(
                left: 124.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 18.0,
                child: GeneratedTambahgambarWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 300.0016784667969,
                height: 1.0,
                child: GeneratedLine99Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 300.0016784667969,
                height: 1.0,
                child: GeneratedLine100Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 300.0016784667969,
                height: 1.0,
                child: GeneratedLine101Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 300.0016784667969,
                height: 1.0,
                child: GeneratedLine102Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 664.0,
                right: null,
                bottom: null,
                width: 300.0016784667969,
                height: 1.0,
                child: GeneratedLine103Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 720.0,
                right: null,
                bottom: null,
                width: 300.0016784667969,
                height: 1.0,
                child: GeneratedLine104Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget16(),
              ),
              Positioned(
                left: 23.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconhomeWidget10(),
              ),
              Positioned(
                left: 121.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget51(),
              )
            ]),
      ),
    ));
  }
}
