import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaiandalemwidget/generated/GeneratedFotoProdukWidget7.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaiandalemwidget/generated/GeneratedKetikanSesuatuWidget.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaiandalemwidget/generated/GeneratedRectangle161Widget2.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaiandalemwidget/generated/GeneratedRectangle163Widget.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaiandalemwidget/generated/GeneratedKirimWidget.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaiandalemwidget/generated/GeneratedAtasWidget16.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaiandalemwidget/generated/GeneratedJudulWidget11.dart';
import 'package:flutterapp/mobilapp/generatedberipenilaiandalemwidget/generated/GeneratedBeriPenilaianWidget3.dart';

/* Frame Beri Penilaian dalem
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBeriPenilaiandalemWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 200.0,
                              child: GeneratedAtasWidget16(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 225.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 68.0,
                              child: GeneratedBeriPenilaianWidget3(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 360.0,
                              right: null,
                              bottom: null,
                              width: 420.0,
                              height: 320.0,
                              child: GeneratedFotoProdukWidget7(),
                            ),
                            Positioned(
                              left: 540.0,
                              top: 360.0,
                              right: null,
                              bottom: null,
                              width: 425.0,
                              height: 61.0,
                              child: GeneratedJudulWidget11(),
                            ),
                            Positioned(
                              left: 520.0,
                              top: 431.0,
                              right: null,
                              bottom: null,
                              width: 820.0,
                              height: 380.0,
                              child: GeneratedRectangle163Widget(),
                            ),
                            Positioned(
                              left: 550.0,
                              top: 451.0,
                              right: null,
                              bottom: null,
                              width: 204.0,
                              height: 37.0,
                              child: GeneratedKetikanSesuatuWidget(),
                            ),
                            Positioned(
                              left: 1140.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 80.0,
                              child: GeneratedRectangle161Widget2(),
                            ),
                            Positioned(
                              left: 1204.0,
                              top: 854.0,
                              right: null,
                              bottom: null,
                              width: 98.0,
                              height: 58.0,
                              child: GeneratedKirimWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
