import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedWarnaWidget5.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedEditProdukWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedMOBILIKUWidget73.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedRectangle730Widget32.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedRectangle731Widget2.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedRectangle770Widget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedTambahkankeHotSaleWidget1.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedRectangle732Widget2.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedIconhomeWidget26.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedFotoprodukWidget3.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedDeskripsiProdukDesainDasborPenuhBaruyangMencolokTipe15G4.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedAtaslogoWidget38.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedRattingWidget3.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedKelolaKomentarWidget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedRectangle539Widget35.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedLine225Widget.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedToyotaAvanzaAllNewGTypeWidget4.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedIconchatWidget30.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedKomenWidget9.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedRp255100000Widget5.dart';
import 'package:flutterapp/mobilapp/generatedklikprodukadminwidget/generated/GeneratedDesprodukWidget3.dart';

/* Frame Klik produk admin
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKlikprodukadminWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 360.0,
        height: 868.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 300.0,
                child: GeneratedFotoprodukWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 150.0,
                child: GeneratedDesprodukWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 214.0,
                height: 22.0,
                child: GeneratedToyotaAvanzaAllNewGTypeWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 22.0,
                child: GeneratedRp255100000Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 130.0,
                child: GeneratedKomenWidget9(),
              ),
              Positioned(
                left: 250.0,
                top: 393.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 25.0,
                child: GeneratedWarnaWidget5(),
              ),
              Positioned(
                left: 290.0,
                top: 434.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 30.0,
                child: GeneratedRattingWidget3(),
              ),
              Positioned(
                left: 340.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 300.0,
                child: GeneratedRectangle539Widget35(),
              ),
              Positioned(
                left: 30.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 135.0,
                child:
                    GeneratedDeskripsiProdukDesainDasborPenuhBaruyangMencolokTipe15G4(),
              ),
              Positioned(
                left: 0.0,
                top: 800.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 68.0,
                child: GeneratedRectangle730Widget32(),
              ),
              Positioned(
                left: 35.0,
                top: 811.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 31.0,
                child: GeneratedRectangle731Widget2(),
              ),
              Positioned(
                left: 18.0,
                top: 842.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 17.0,
                child: GeneratedEditProdukWidget1(),
              ),
              Positioned(
                left: 102.0,
                top: 842.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 17.0,
                child: GeneratedKelolaKomentarWidget(),
              ),
              Positioned(
                left: 200.0,
                top: 800.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 68.0,
                child: GeneratedRectangle732Widget2(),
              ),
              Positioned(
                left: 212.0,
                top: 813.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 44.0,
                child: GeneratedTambahkankeHotSaleWidget1(),
              ),
              Positioned(
                left: 94.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 1.0,
                child: GeneratedLine225Widget(),
              ),
              Positioned(
                left: 129.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 35.0,
                child: GeneratedRectangle770Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 50.0,
                child: GeneratedAtaslogoWidget38(),
              ),
              Positioned(
                left: 23.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconhomeWidget26(),
              ),
              Positioned(
                left: 312.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 25.0,
                child: GeneratedIconchatWidget30(),
              ),
              Positioned(
                left: 121.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 28.0,
                child: GeneratedMOBILIKUWidget73(),
              )
            ]),
      ),
    ));
  }
}
