import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedchat2widget/generated/GeneratedAtasWidget3.dart';
import 'package:flutterapp/mobilapp/generatedchat2widget/generated/GeneratedBawahWidget.dart';
import 'package:flutterapp/mobilapp/generatedchat2widget/generated/GeneratedNamaakunchatWidget.dart';
import 'package:flutterapp/mobilapp/generatedchat2widget/generated/GeneratedProfilechatWidget.dart';
import 'package:flutterapp/mobilapp/generatedchat2widget/generated/GeneratedKetikanpesanWidget.dart';
import 'package:flutterapp/mobilapp/generatedchat2widget/generated/GeneratedTombolkirimWidget.dart';

/* Frame Chat 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChat2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0008544921875,
                              height: 220.0,
                              child: GeneratedAtasWidget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 920.0,
                              right: null,
                              bottom: null,
                              width: 1440.0008544921875,
                              height: 104.0,
                              child: GeneratedBawahWidget(),
                            ),
                            Positioned(
                              left: 640.0,
                              top: 12.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 160.0,
                              child: GeneratedProfilechatWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 940.0,
                              right: null,
                              bottom: null,
                              width: 1250.0,
                              height: 69.0,
                              child: GeneratedKetikanpesanWidget(),
                            ),
                            Positioned(
                              left: 1320.0,
                              top: 940.0,
                              right: null,
                              bottom: null,
                              width: 69.0,
                              height: 69.0,
                              child: GeneratedTombolkirimWidget(),
                            ),
                            Positioned(
                              left: 629.0,
                              top: 182.0,
                              right: null,
                              bottom: null,
                              width: 182.0,
                              height: 26.0,
                              child: GeneratedNamaakunchatWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
