import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle149Widget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle152Widget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle154Widget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedJenisMobilBaruBekasWidget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedLine41Widget2.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedLine36Widget9.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle151Widget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedJudulWidget4.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle157Widget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedLine40Widget2.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedAtasWidget10.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle155Widget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle147Widget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedLine37Widget9.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedLine38Widget3.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle156Widget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle153Widget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle150Widget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedBayarSekarangWidget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedNamaPemesanWidget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedJenisPembayaranWidget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle158Widget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedAlamatPemesanWidget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle148Widget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedLine39Widget3.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedHargaWidget4.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedWarnamobilWidget.dart';
import 'package:flutterapp/mobilapp/generatedlayoutcheckoutwidget/generated/GeneratedRectangle159Widget.dart';

/* Frame Layout checkout 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLayoutcheckoutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2000.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 2000.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 200.0,
                              child: GeneratedAtasWidget10(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 280.0,
                              right: null,
                              bottom: null,
                              width: 420.0,
                              height: 320.0,
                              child: GeneratedRectangle147Widget(),
                            ),
                            Positioned(
                              left: 100.0,
                              top: 611.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 91.0,
                              child: GeneratedJudulWidget4(),
                            ),
                            Positioned(
                              left: 560.0,
                              top: 260.0,
                              right: null,
                              bottom: null,
                              width: 800.0,
                              height: 250.0,
                              child: GeneratedRectangle148Widget(),
                            ),
                            Positioned(
                              left: 600.0,
                              top: 300.0,
                              right: null,
                              bottom: null,
                              width: 720.0,
                              height: 70.0,
                              child: GeneratedRectangle149Widget(),
                            ),
                            Positioned(
                              left: 600.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 720.0,
                              height: 70.0,
                              child: GeneratedRectangle150Widget(),
                            ),
                            Positioned(
                              left: 620.0,
                              top: 350.0,
                              right: null,
                              bottom: null,
                              width: 680.0,
                              height: 1.0,
                              child: GeneratedLine36Widget9(),
                            ),
                            Positioned(
                              left: 620.0,
                              top: 450.0,
                              right: null,
                              bottom: null,
                              width: 680.0,
                              height: 1.0,
                              child: GeneratedLine37Widget9(),
                            ),
                            Positioned(
                              left: 620.0,
                              top: 315.0,
                              right: null,
                              bottom: null,
                              width: 311.0,
                              height: 37.0,
                              child: GeneratedJenisMobilBaruBekasWidget(),
                            ),
                            Positioned(
                              left: 620.0,
                              top: 415.0,
                              right: null,
                              bottom: null,
                              width: 169.0,
                              height: 37.0,
                              child: GeneratedWarnamobilWidget(),
                            ),
                            Positioned(
                              left: 560.0,
                              top: 540.0,
                              right: null,
                              bottom: null,
                              width: 800.0,
                              height: 420.0,
                              child: GeneratedRectangle151Widget(),
                            ),
                            Positioned(
                              left: 600.0,
                              top: 565.0,
                              right: null,
                              bottom: null,
                              width: 720.0,
                              height: 70.0,
                              child: GeneratedRectangle152Widget(),
                            ),
                            Positioned(
                              left: 600.0,
                              top: 660.0,
                              right: null,
                              bottom: null,
                              width: 720.0,
                              height: 70.0,
                              child: GeneratedRectangle153Widget(),
                            ),
                            Positioned(
                              left: 600.0,
                              top: 760.0,
                              right: null,
                              bottom: null,
                              width: 720.0,
                              height: 70.0,
                              child: GeneratedRectangle154Widget(),
                            ),
                            Positioned(
                              left: 620.0,
                              top: 615.0,
                              right: null,
                              bottom: null,
                              width: 680.0,
                              height: 1.0,
                              child: GeneratedLine38Widget3(),
                            ),
                            Positioned(
                              left: 620.0,
                              top: 710.0,
                              right: null,
                              bottom: null,
                              width: 680.0,
                              height: 1.0,
                              child: GeneratedLine39Widget3(),
                            ),
                            Positioned(
                              left: 620.0,
                              top: 810.0,
                              right: null,
                              bottom: null,
                              width: 680.0,
                              height: 1.0,
                              child: GeneratedLine40Widget2(),
                            ),
                            Positioned(
                              left: 620.0,
                              top: 577.0,
                              right: null,
                              bottom: null,
                              width: 199.0,
                              height: 37.0,
                              child: GeneratedNamaPemesanWidget(),
                            ),
                            Positioned(
                              left: 620.0,
                              top: 672.0,
                              right: null,
                              bottom: null,
                              width: 215.0,
                              height: 37.0,
                              child: GeneratedAlamatPemesanWidget(),
                            ),
                            Positioned(
                              left: 620.0,
                              top: 772.0,
                              right: null,
                              bottom: null,
                              width: 230.0,
                              height: 37.0,
                              child: GeneratedJenisPembayaranWidget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 760.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 80.0,
                              child: GeneratedRectangle155Widget(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 760.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 80.0,
                              child: GeneratedRectangle156Widget(),
                            ),
                            Positioned(
                              left: 360.0,
                              top: 760.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 80.0,
                              child: GeneratedRectangle157Widget(),
                            ),
                            Positioned(
                              left: 580.0,
                              top: 1000.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 80.0,
                              child: GeneratedRectangle158Widget(),
                            ),
                            Positioned(
                              left: 625.0,
                              top: 1022.0,
                              right: null,
                              bottom: null,
                              width: 193.0,
                              height: 37.0,
                              child: GeneratedBayarSekarangWidget(),
                            ),
                            Positioned(
                              left: 960.0,
                              top: 860.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 70.0,
                              child: GeneratedRectangle159Widget(),
                            ),
                            Positioned(
                              left: 980.0,
                              top: 911.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 1.0,
                              child: GeneratedLine41Widget2(),
                            ),
                            Positioned(
                              left: 987.0,
                              top: 879.0,
                              right: null,
                              bottom: null,
                              width: 315.0,
                              height: 37.0,
                              child: GeneratedHargaWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
