import 'package:flutter/material.dart';
import 'package:flutterapp/mobilapp/generateddesktop2widget/generated/GeneratedColorHuntPalette21325e3e497af1d00af0f0f011Widget.dart';

/* Frame Desktop - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesktop2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 54.0,
                              right: null,
                              bottom: null,
                              width: 400.0,
                              height: 400.0,
                              child:
                                  GeneratedColorHuntPalette21325e3e497af1d00af0f0f011Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
