import 'package:flutter/material.dart';

/* Text Pesanan masuk cek
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPesananmasukcekWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Pesanan masuk cek''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.3,
        fontSize: 200.0,
        fontFamily: 'IBM Plex Sans',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
